In [1]:
print("PRAISE THE LORD ALMIGHTY FATHER Thank You JESUS Praise You JESUS Forever May the HOLY SPIRIT Guide Us MOTHER MARY PRAY For Us SAINT JOSEPH, PRAY For Us SAINT ANTHONY PRAY For Us GOD BLESS !!! üß°‚õ™‚úù‚õ™üß°")

PRAISE THE LORD ALMIGHTY FATHER Thank You JESUS Praise You JESUS Forever May the HOLY SPIRIT Guide Us MOTHER MARY PRAY For Us SAINT JOSEPH, PRAY For Us SAINT ANTHONY PRAY For Us GOD BLESS !!! üß°‚õ™‚úù‚õ™üß°

In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

## This note book Includes data from 2018 onwards

In [5]:
df_matches = pd.read_csv('2022_to_2023_all_matches.csv')

## Pre Processings

In [6]:
#Engineer the Run Rate according to the following rules 
def getRequiredRunRate_first_innings(over , wickets):
  if over < 6:
    if wickets < 1:
      return 10
    elif wickets>=1 and wickets<4:
      return  8
    else:
      6
  elif over >= 6 and over<15:
    if wickets < 1:
      return 11
    elif wickets>=1 and wickets<4:
      return  9
    elif wickets>=4 and wickets<6:
      return 8
    else:
      return 6  
  elif over >= 15 and over<20:
    if wickets < 1:
      return 15
    elif wickets>=1 and wickets<7:
      return  12
    else :
      return 10
    # code block 3

current_index = 0

while current_index < len(df_matches):
   if(df_matches['innings'][current_index] == 1):
     #print('Addding the First Innings Required Run Rate index is ' ,current_index)
     df_matches['req_run_rate'][current_index] = getRequiredRunRate_first_innings(df_matches['over'][current_index] , df_matches['over_start_total_wickets_fallen'][current_index])
   current_index = current_index + 1

C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\2851207831.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches['req_run_rate'][current_index] = getRequiredRunRate_first_innings(df_matches['over'][current_index] , df_matches['over_start_total_wickets_fallen'][current_index])

In [7]:
df_matches['date'] = df_matches['year'].apply(lambda x: x[1:-1])

In [8]:
df_matches['date'] = pd.to_datetime(df_matches['date'])

In [9]:
df_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19110 entries, 0 to 19109
Data columns (total 65 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 19110 non-null  int64
 1   year                                       19110 non-null  object
 2   over_start_bowler_balls_bowled             19110 non-null  int64
 3   over_start_bowler_wickets_taken            19110 non-null  int64
 4   over_start_bowler_runs_given               19110 non-null  int64
 5   over_start_batsman_on_strike_fours         19110 non-null  int64
 6   over_start_batsman_on_strike_sixers        19110 non-null  int64
 7   over_start_batsman_off_strike_balls_faced  19110 non-null  int64
 8   over_start_batsman_on_strike_balls_faced   19110 non-null  int64
 9   over_start_batsman_offstrike_runs          19110 non-null  int64
 10  over_start_batsman_onstrike_runs           19110 non-null  int64
 11  innings                                    19110 non-null  int64
 12  match_num                                  19110 non-null  int64
 13  country                                    19110 non-null  object
 14  target                                     19110 non-null  int64
 15  req_run_rate                               19091 non-null  float64
 16  over_start_run_rate                        19110 non-null  float64
 17  over_start_total_score                     19110 non-null  int64
 18  over_start_total_wickets_fallen            19110 non-null  int64
 19  over                                       19110 non-null  int64
 20  Bowler                                     19110 non-null  object
 21  batter_onStrike                            19110 non-null  object
 22  batter_offstrike                           19110 non-null  object
 23  wickets_fallen                             19110 non-null  int64
 24  sixers                                     19110 non-null  int64
 25  fours                                      19110 non-null  int64
 26  total_runs                                 19110 non-null  int64
 27  bat_on_str_Ave                             18642 non-null  object
 28  bat_on_str_SR                              18642 non-null  object
 29  bat_on_str_100                             18642 non-null  object
 30  bat_on_str_50                              18642 non-null  object
 31  bat_on_str_0                               18642 non-null  object
 32  bat_on_str_4s                              18642 non-null  object
 33  bat_on_str_6s                              18642 non-null  object
 34  bat_on_str_Mat                             18642 non-null  float64
 35  bat_on_str_Inns                            18642 non-null  object
 36  bat_on_str_NO                              18642 non-null  object
 37  bat_on_str_Runs                            18642 non-null  object
 38  bat_on_str_HS                              18642 non-null  object
 39  bat_on_str_BF                              18642 non-null  object
 40  bowler_Mat                                 18374 non-null  float64
 41  bowler_Inns                                18374 non-null  object
 42  bowler_Overs                               18374 non-null  object
 43  bowler_Mdns                                18374 non-null  object
 44  bowler_Runs                                18374 non-null  object
 45  bowler_Wkts                                18374 non-null  object
 46  bowler_Ave                                 18374 non-null  object
 47  bowler_Econ                                18374 non-null  object
 48  bowler_SR                                  18374 non-null  object
 49  bowler_4w                                  18374 non-null  object
 50  bowler_5w                                  18374 non-null  object
 51  bat_off_str_Ave                            18611 non-null  object
 52  bat_off_str_SR                             18611 non-null  object
 53  bat_off_str_100                            18611 non-null  object
 54  bat_off_str_50                             18611 non-null  object
 55  bat_off_str_0                              18611 non-null  object
 56  bat_off_str_4s                             18611 non-null  object
 57  bat_off_str_6s                             18611 non-null  object
 58  bat_off_str_Mat                            18611 non-null  float64
 59  bat_off_str_Inns                           18611 non-null  object
 60  bat_off_str_NO                             18611 non-null  object
 61  bat_off_str_Runs                           18611 non-null  object
 62  bat_off_str_HS                             18611 non-null  object
 63  bat_off_str_BF                             18611 non-null  object
 64  date                                       19110 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(20), object(39)
memory usage: 9.5+ MB

In [10]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Checking Null Values

In [11]:

# Iterate over the columns
for column in df_matches.columns:
    # Count the number of null values in the column
    null_count = df_matches[column].isnull().sum()

    # Display the column name and the number of null values
    print(f"Column '{column}' has {null_count} null values.")

Column 'Unnamed: 0' has 0 null values.
Column 'year' has 0 null values.
Column 'over_start_bowler_balls_bowled' has 0 null values.
Column 'over_start_bowler_wickets_taken' has 0 null values.
Column 'over_start_bowler_runs_given' has 0 null values.
Column 'over_start_batsman_on_strike_fours' has 0 null values.
Column 'over_start_batsman_on_strike_sixers' has 0 null values.
Column 'over_start_batsman_off_strike_balls_faced' has 0 null values.
Column 'over_start_batsman_on_strike_balls_faced' has 0 null values.
Column 'over_start_batsman_offstrike_runs' has 0 null values.
Column 'over_start_batsman_onstrike_runs' has 0 null values.
Column 'innings' has 0 null values.
Column 'match_num' has 0 null values.
Column 'country' has 0 null values.
Column 'target' has 0 null values.
Column 'req_run_rate' has 19 null values.
Column 'over_start_run_rate' has 0 null values.
Column 'over_start_total_score' has 0 null values.
Column 'over_start_total_wickets_fallen' has 0 null values.
Column 'over' has 0 null values.
Column 'Bowler' has 0 null values.
Column 'batter_onStrike' has 0 null values.
Column 'batter_offstrike' has 0 null values.
Column 'wickets_fallen' has 0 null values.
Column 'sixers' has 0 null values.
Column 'fours' has 0 null values.
Column 'total_runs' has 0 null values.
Column 'bat_on_str_Ave' has 468 null values.
Column 'bat_on_str_SR' has 468 null values.
Column 'bat_on_str_100' has 468 null values.
Column 'bat_on_str_50' has 468 null values.
Column 'bat_on_str_0' has 468 null values.
Column 'bat_on_str_4s' has 468 null values.
Column 'bat_on_str_6s' has 468 null values.
Column 'bat_on_str_Mat' has 468 null values.
Column 'bat_on_str_Inns' has 468 null values.
Column 'bat_on_str_NO' has 468 null values.
Column 'bat_on_str_Runs' has 468 null values.
Column 'bat_on_str_HS' has 468 null values.
Column 'bat_on_str_BF' has 468 null values.
Column 'bowler_Mat' has 736 null values.
Column 'bowler_Inns' has 736 null values.
Column 'bowler_Overs' has 736 null values.
Column 'bowler_Mdns' has 736 null values.
Column 'bowler_Runs' has 736 null values.
Column 'bowler_Wkts' has 736 null values.
Column 'bowler_Ave' has 736 null values.
Column 'bowler_Econ' has 736 null values.
Column 'bowler_SR' has 736 null values.
Column 'bowler_4w' has 736 null values.
Column 'bowler_5w' has 736 null values.
Column 'bat_off_str_Ave' has 499 null values.
Column 'bat_off_str_SR' has 499 null values.
Column 'bat_off_str_100' has 499 null values.
Column 'bat_off_str_50' has 499 null values.
Column 'bat_off_str_0' has 499 null values.
Column 'bat_off_str_4s' has 499 null values.
Column 'bat_off_str_6s' has 499 null values.
Column 'bat_off_str_Mat' has 499 null values.
Column 'bat_off_str_Inns' has 499 null values.
Column 'bat_off_str_NO' has 499 null values.
Column 'bat_off_str_Runs' has 499 null values.
Column 'bat_off_str_HS' has 499 null values.
Column 'bat_off_str_BF' has 499 null values.
Column 'date' has 0 null values.

In [12]:
## Replacing Null Values with Null

object_columns = ['wickets_fallen', 'sixers', 'fours', 'total_runs',
       'bat_on_str_Ave', 'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50',
       'bat_on_str_0', 'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat',
       'bat_on_str_Inns', 'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS',
       'bat_on_str_BF', 'bowler_Mat', 'bowler_Inns', 'bowler_Overs',
       'bowler_Mdns', 'bowler_Runs', 'bowler_Wkts', 'bowler_Ave',
       'bowler_Econ', 'bowler_SR', 'bowler_4w', 'bowler_5w', 'bat_off_str_Ave',
       'bat_off_str_SR', 'bat_off_str_100', 'bat_off_str_50', 'bat_off_str_0',
       'bat_off_str_4s', 'bat_off_str_6s', 'bat_off_str_Mat',
       'bat_off_str_Inns', 'bat_off_str_NO', 'bat_off_str_Runs',
       'bat_off_str_HS', 'bat_off_str_BF']


for col in object_columns :
    df_matches[col].replace({'-': np.NaN , '':np.NaN , 'nan':np.NaN},inplace=True)

In [13]:
#Remove the star value in Batsman High Score

current_index = 0

while current_index < len(df_matches):
   try:
    df_matches['bat_off_str_HS'][current_index] = df_matches['bat_off_str_HS'][current_index].replace("*" , "")
   except:
     print("All good" , current_index)

   try:
    df_matches['bat_on_str_HS'][current_index] = df_matches['bat_on_str_HS'][current_index].replace("*" , "")
   except:
     print("All good" , current_index)
   
   current_index = current_index + 1

C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\1425456917.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches['bat_off_str_HS'][current_index] = df_matches['bat_off_str_HS'][current_index].replace("*" , "")
C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\1425456917.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches['bat_on_str_HS'][current_index] = df_matches['bat_on_str_HS'][current_index].replace("*" , "")

All good 2
All good 3
All good 4
All good 5
All good 6
All good 7
All good 8
All good 9
All good 10
All good 11
All good 12
All good 13
All good 20
All good 21
All good 22
All good 23
All good 24
All good 25
All good 563
All good 704
All good 705
All good 706
All good 707
All good 708
All good 744
All good 745
All good 746
All good 747
All good 748
All good 749
All good 750
All good 751
All good 752
All good 753
All good 754
All good 755
All good 756
All good 757
All good 758
All good 976
All good 1111
All good 1112
All good 1113
All good 1114
All good 1115
All good 1116
All good 1117
All good 1118
All good 1119
All good 1120
All good 1121
All good 1122
All good 1123
All good 1124
All good 1125
All good 1126
All good 1255
All good 1256
All good 1256
All good 1257
All good 1257
All good 1258
All good 1258
All good 1259
All good 1259
All good 1260
All good 1260
All good 1261
All good 1261
All good 1262
All good 1296
All good 1297
All good 1298
All good 1355
All good 1375
All good 1419
All good 1420
All good 1421
All good 1422
All good 1423
All good 1424
All good 1425
All good 1426
All good 1427
All good 1428
All good 1429
All good 1430
All good 1431
All good 1432
All good 1433
All good 1434
All good 1435
All good 1841
All good 1842
All good 2164
All good 2165
All good 2183
All good 2184
All good 2209
All good 2210
All good 2211
All good 2212
All good 2213
All good 2214
All good 2261
All good 2262
All good 2297
All good 2584
All good 2585
All good 2702
All good 2703
All good 2704
All good 2705
All good 2712
All good 2713
All good 2714
All good 2715
All good 2716
All good 2729
All good 2730
All good 2731
All good 2733
All good 2734
All good 2743
All good 2744
All good 2745
All good 2746
All good 2747
All good 2748
All good 2807
All good 2817
All good 2818
All good 2820
All good 2821
All good 2827
All good 2847
All good 3090
All good 3091
All good 3092
All good 3215
All good 3330
All good 3369
All good 3370
All good 3371
All good 3476
All good 3477
All good 3478
All good 3479
All good 3480
All good 3481
All good 3482
All good 3483
All good 3484
All good 3779
All good 3852
All good 3853
All good 3854
All good 3855
All good 3856
All good 3857
All good 3858
All good 3909
All good 4201
All good 4202
All good 4267
All good 4268
All good 4269
All good 4270
All good 4271
All good 4272
All good 4273
All good 4274
All good 4275
All good 4497
All good 4498
All good 4562
All good 4563
All good 4564
All good 4640
All good 4641
All good 4642
All good 4643
All good 4644
All good 4645
All good 4646
All good 4647
All good 4648
All good 4652
All good 4653
All good 4711
All good 4712
All good 5740
All good 5741
All good 5800
All good 5801
All good 5802
All good 5862
All good 5876
All good 5877
All good 5878
All good 5879
All good 5994
All good 5998
All good 5999
All good 6000
All good 6001
All good 6002
All good 6003
All good 6004
All good 6005
All good 6073
All good 6084
All good 6085
All good 6086
All good 6138
All good 6153
All good 6154
All good 6157
All good 6158
All good 6296
All good 6297
All good 6337
All good 6338
All good 6339
All good 6340
All good 6341
All good 6342
All good 6343
All good 6344
All good 6345
All good 6346
All good 6347
All good 6348
All good 6349
All good 6350
All good 6351
All good 6352
All good 6353
All good 6354
All good 6355
All good 6356
All good 6372
All good 6373
All good 6374
All good 6521
All good 6532
All good 6534
All good 6535
All good 6536
All good 6537
All good 6565
All good 6566
All good 6567
All good 6568
All good 6571
All good 6583
All good 6584
All good 6585
All good 6586
All good 6587
All good 6588
All good 6589
All good 6682
All good 6683
All good 6684
All good 6920
All good 6921
All good 6922
All good 6923
All good 6924
All good 6925
All good 6926
All good 6927
All good 6928
All good 6929
All good 6933
All good 6934
All good 6935
All good 6936
All good 6937
All good 6942
All good 6992
All good 7026
All good 7054
All good 7055
All good 7056
All good 7057
All good 7058
All good 7059
All good 7060
All good 7061
All good 7062
All good 7063
All good 7064
All good 7065
All good 7066
All good 7067
All good 7084
All good 7085
All good 7086
All good 7087
All good 7088
All good 7169
All good 7169
All good 7170
All good 7170
All good 7171
All good 7171
All good 7172
All good 7172
All good 7173
All good 7173
All good 7174
All good 7174
All good 7175
All good 7175
All good 7176
All good 7176
All good 7177
All good 7177
All good 7212
All good 7213
All good 7417
All good 7422
All good 7423
All good 7424
All good 7425
All good 7426
All good 7427
All good 7428
All good 7429
All good 7502
All good 7503
All good 7504
All good 7505
All good 7506
All good 7507
All good 7508
All good 7509
All good 7510
All good 7511
All good 7512
All good 7513
All good 7569
All good 7600
All good 7601
All good 8011
All good 8012
All good 8013
All good 8014
All good 8015
All good 8016
All good 8017
All good 8018
All good 8019
All good 8020
All good 8021
All good 8022
All good 8023
All good 8024
All good 8025
All good 8026
All good 8146
All good 8164
All good 8164
All good 8165
All good 8165
All good 8166
All good 8166
All good 8220
All good 8221
All good 8222
All good 8223
All good 8224
All good 8225
All good 8225
All good 8404
All good 8625
All good 8626
All good 8627
All good 8628
All good 8629
All good 8630
All good 8631
All good 8671
All good 8730
All good 8731
All good 8732
All good 8732
All good 8733
All good 8734
All good 8739
All good 8810
All good 8811
All good 8812
All good 8813
All good 8814
All good 8815
All good 8816
All good 8817
All good 8818
All good 8819
All good 8870
All good 8871
All good 8872
All good 8873
All good 8874
All good 8875
All good 8876
All good 8877
All good 8878
All good 8879
All good 8880
All good 8881
All good 8882
All good 8890
All good 9019
All good 9023
All good 9024
All good 9025
All good 9026
All good 9027
All good 9028
All good 9029
All good 9030
All good 9031
All good 9032
All good 9037
All good 9038
All good 9039
All good 9128
All good 9129
All good 9130
All good 9134
All good 9135
All good 9136
All good 9137
All good 9138
All good 9139
All good 9140
All good 9151
All good 9152
All good 9298
All good 9299
All good 9300
All good 9301
All good 9315
All good 9316
All good 9338
All good 9339
All good 9340
All good 9395
All good 9396
All good 9454
All good 9455
All good 9456
All good 9457
All good 9477
All good 9504
All good 9504
All good 9505
All good 9505
All good 9595
All good 9596
All good 9612
All good 9683
All good 9684
All good 9685
All good 9686
All good 9687
All good 9703
All good 9710
All good 9711
All good 9712
All good 9713
All good 9714
All good 9715
All good 9716
All good 9717
All good 9718
All good 9719
All good 9740
All good 9741
All good 9742
All good 9770
All good 9771
All good 9772
All good 9773
All good 9815
All good 9816
All good 9817
All good 9818
All good 9819
All good 9820
All good 9821
All good 9822
All good 9859
All good 9860
All good 9861
All good 9862
All good 9989
All good 9990
All good 9991
All good 9992
All good 9993
All good 9994
All good 10129
All good 10130
All good 10131
All good 10132
All good 10133
All good 10134
All good 10135
All good 10389
All good 10422
All good 10423
All good 10424
All good 10425
All good 10426
All good 10443
All good 10522
All good 10523
All good 10524
All good 10525
All good 10526
All good 10527
All good 10528
All good 10529
All good 10530
All good 10531
All good 10532
All good 10533
All good 10602
All good 10602
All good 10603
All good 10603
All good 10624
All good 10625
All good 10626
All good 10627
All good 10628
All good 10629
All good 10630
All good 10631
All good 10650
All good 10651
All good 10652
All good 10653
All good 10654
All good 10655
All good 10656
All good 10657
All good 10658
All good 10659
All good 10660
All good 10661
All good 10662
All good 10793
All good 10794
All good 10795
All good 10796
All good 10797
All good 10798
All good 10799
All good 10800
All good 10801
All good 10802
All good 10802
All good 10803
All good 10803
All good 10804
All good 10804
All good 10805
All good 10805
All good 10806
All good 10807
All good 10809
All good 10810
All good 10811
All good 10863
All good 10864
All good 10889
All good 10930
All good 10931
All good 10932
All good 10933
All good 11100
All good 11101
All good 11141
All good 11142
All good 11143
All good 11327
All good 11328
All good 11354
All good 11411
All good 11412
All good 11413
All good 11414
All good 11415
All good 11520
All good 11521
All good 11522
All good 11573
All good 11764
All good 11765
All good 11860
All good 11908
All good 11909
All good 11910
All good 11911
All good 11912
All good 11912
All good 11913
All good 11913
All good 11914
All good 11914
All good 11915
All good 11916
All good 11976
All good 12007
All good 12007
All good 12008
All good 12008
All good 12009
All good 12009
All good 12010
All good 12010
All good 12030
All good 12031
All good 12032
All good 12033
All good 12072
All good 12073
All good 12074
All good 12075
All good 12076
All good 12077
All good 12080
All good 12081
All good 12082
All good 12083
All good 12087
All good 12088
All good 12109
All good 12110
All good 12111
All good 12127
All good 12128
All good 12129
All good 12241
All good 12242
All good 12243
All good 12244
All good 12245
All good 12246
All good 12247
All good 12248
All good 12249
All good 12250
All good 12316
All good 12317
All good 12318
All good 12319
All good 12320
All good 12321
All good 12322
All good 12323
All good 12324
All good 12325
All good 12378
All good 12379
All good 12380
All good 12381
All good 12382
All good 12392
All good 12393
All good 12394
All good 12395
All good 12396
All good 12397
All good 12398
All good 12399
All good 12400
All good 12401
All good 12402
All good 12403
All good 12404
All good 12405
All good 12406
All good 12450
All good 12486
All good 12487
All good 12592
All good 12607
All good 12668
All good 12690
All good 12704
All good 12705
All good 12705
All good 12706
All good 12707
All good 12725
All good 12726
All good 12727
All good 12774
All good 12775
All good 12865
All good 12866
All good 12872
All good 12873
All good 12874
All good 12875
All good 12900
All good 12901
All good 12902
All good 12903
All good 12904
All good 12905
All good 12906
All good 12907
All good 12908
All good 12909
All good 12934
All good 12935
All good 12975
All good 12975
All good 13027
All good 13028
All good 13029
All good 13030
All good 13031
All good 13032
All good 13033
All good 13169
All good 13182
All good 13183
All good 13189
All good 13223
All good 13224
All good 13225
All good 13226
All good 13227
All good 13228
All good 13229
All good 13245
All good 13246
All good 13247
All good 13422
All good 13423
All good 13424
All good 13430
All good 13431
All good 13432
All good 13433
All good 13434
All good 13435
All good 13436
All good 13437
All good 13499
All good 13499
All good 13500
All good 13500
All good 13501
All good 13501
All good 13502
All good 13502
All good 13503
All good 13503
All good 13504
All good 13504
All good 13505
All good 13505
All good 13511
All good 13512
All good 13513
All good 13514
All good 13517
All good 13518
All good 13519
All good 13581
All good 13582
All good 13600
All good 13601
All good 13602
All good 13603
All good 13604
All good 13616
All good 13617
All good 13618
All good 13619
All good 13620
All good 13621
All good 13645
All good 13646
All good 13647
All good 13648
All good 13649
All good 13717
All good 13813
All good 13813
All good 13878
All good 13879
All good 13880
All good 13881
All good 13882
All good 13883
All good 13884
All good 13885
All good 13886
All good 13887
All good 13888
All good 13889
All good 13890
All good 13890
All good 13891
All good 13891
All good 13899
All good 13900
All good 13901
All good 14050
All good 14138
All good 14139
All good 14164
All good 14171
All good 14172
All good 14216
All good 14243
All good 14244
All good 14245
All good 14246
All good 14247
All good 14248
All good 14249
All good 14250
All good 14251
All good 14252
All good 14260
All good 14261
All good 14262
All good 14263
All good 14264
All good 14265
All good 14266
All good 14267
All good 14268
All good 14269
All good 14270
All good 14271
All good 14272
All good 14273
All good 14274
All good 14282
All good 14283
All good 14359
All good 14360
All good 14361
All good 14421
All good 14480
All good 14481
All good 14481
All good 14501
All good 14519
All good 14520
All good 14521
All good 14531
All good 14532
All good 14541
All good 14752
All good 14753
All good 14754
All good 14755
All good 14756
All good 14757
All good 14758
All good 14759
All good 14760
All good 14761
All good 14762
All good 14763
All good 14764
All good 14765
All good 14766
All good 14846
All good 14861
All good 14861
All good 14862
All good 14862
All good 14863
All good 14863
All good 14864
All good 14865
All good 14866
All good 14867
All good 14868
All good 14906
All good 14907
All good 14908
All good 14909
All good 14910
All good 14911
All good 14912
All good 14913
All good 14914
All good 15026
All good 15027
All good 15028
All good 15029
All good 15044
All good 15044
All good 15045
All good 15045
All good 15135
All good 15135
All good 15136
All good 15136
All good 15137
All good 15137
All good 15138
All good 15138
All good 15141
All good 15223
All good 15224
All good 15225
All good 15226
All good 15227
All good 15228
All good 15229
All good 15230
All good 15231
All good 15232
All good 15233
All good 15234
All good 15235
All good 15295
All good 15296
All good 15422
All good 15423
All good 15424
All good 15425
All good 15426
All good 15427
All good 15428
All good 15429
All good 15430
All good 15431
All good 15432
All good 15434
All good 15444
All good 15445
All good 15446
All good 15447
All good 15448
All good 15449
All good 15450
All good 15489
All good 15645
All good 15646
All good 15647
All good 15748
All good 15749
All good 15750
All good 15785
All good 15786
All good 15863
All good 15882
All good 15919
All good 15920
All good 15921
All good 15922
All good 15956
All good 15957
All good 15958
All good 15959
All good 15960
All good 15961
All good 16020
All good 16021
All good 16022
All good 16023
All good 16085
All good 16086
All good 16087
All good 16088
All good 16089
All good 16090
All good 16091
All good 16347
All good 16378
All good 16565
All good 16566
All good 16567
All good 16603
All good 16604
All good 16660
All good 16745
All good 16746
All good 16747
All good 16748
All good 16749
All good 16750
All good 16751
All good 16752
All good 16753
All good 16754
All good 16755
All good 16787
All good 16788
All good 16789
All good 16790
All good 16791
All good 16792
All good 16793
All good 16794
All good 16867
All good 16868
All good 16869
All good 16870
All good 16871
All good 16872
All good 16911
All good 16912
All good 17037
All good 17038
All good 17039
All good 17040
All good 17041
All good 17042
All good 17043
All good 17044
All good 17045
All good 17046
All good 17047
All good 17048
All good 17049
All good 17050
All good 17075
All good 17076
All good 17077
All good 17078
All good 17079
All good 17080
All good 17081
All good 17082
All good 17083
All good 17084
All good 17091
All good 17248
All good 17248
All good 17324
All good 17325
All good 17326
All good 17327
All good 17328
All good 17329
All good 17330
All good 17478
All good 17479
All good 17553
All good 17554
All good 17555
All good 17556
All good 17607
All good 17607
All good 17608
All good 17608
All good 17609
All good 17609
All good 17610
All good 17610
All good 17611
All good 17611
All good 17612
All good 17612
All good 17613
All good 17613
All good 17614
All good 17614
All good 17615
All good 17615
All good 17616
All good 17616
All good 17672
All good 17673
All good 17674
All good 17675
All good 17676
All good 17677
All good 17678
All good 17679
All good 17680
All good 17681
All good 17682
All good 17683
All good 17684
All good 17685
All good 17686
All good 17687
All good 17693
All good 17694
All good 17695
All good 17751
All good 17774
All good 17774
All good 17775
All good 17775
All good 17793
All good 17794
All good 17795
All good 17814
All good 17815
All good 17815
All good 17862
All good 17897
All good 17938
All good 17939
All good 17940
All good 17941
All good 17942
All good 18020
All good 18021
All good 18031
All good 18045
All good 18045
All good 18046
All good 18046
All good 18047
All good 18047
All good 18048
All good 18048
All good 18049
All good 18049
All good 18088
All good 18089
All good 18090
All good 18091
All good 18092
All good 18093
All good 18094
All good 18095
All good 18096
All good 18097
All good 18098
All good 18099
All good 18161
All good 18162
All good 18331
All good 18449
All good 18512
All good 18513
All good 18514
All good 18515
All good 18516
All good 18517
All good 18518
All good 18577
All good 18577
All good 18578
All good 18578
All good 18579
All good 18579
All good 18642
All good 18643
All good 18644
All good 18645
All good 18646
All good 18647
All good 18648
All good 18649
All good 18650
All good 18651
All good 18652
All good 18653
All good 18944
All good 18945
All good 18946
All good 18947
All good 19009
All good 19009
All good 19010
All good 19010
All good 19011
All good 19011
All good 19062
All good 19063
All good 19070
All good 19071
All good 19085
All good 19086

In [14]:
df_matches.insert(54,"y_is_wicket_fallen", " ")
#Add 1 and 0 if a wicket has fallen in the next over

current_index = 0

while current_index < len(df_matches):
   if df_matches['wickets_fallen'][current_index] > 0:   
      df_matches['y_is_wicket_fallen'][current_index] = 1
   else:
      df_matches['y_is_wicket_fallen'][current_index] = 0
      
   current_index = current_index + 1

C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\2687773729.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches['y_is_wicket_fallen'][current_index] = 0
C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\2687773729.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches['y_is_wicket_fallen'][current_index] = 1

In [15]:
df_matches.columns

Index(['Unnamed: 0', 'year', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'match_num', 'country', 'target', 'req_run_rate',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'Bowler', 'batter_onStrike',
       'batter_offstrike', 'wickets_fallen', 'sixers', 'fours', 'total_runs',
       'bat_on_str_Ave', 'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50',
       'bat_on_str_0', 'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat',
       'bat_on_str_Inns', 'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS',
       'bat_on_str_BF', 'bowler_Mat', 'bowler_Inns', 'bowler_Overs',
       'bowler_Mdns', 'bowler_Runs', 'bowler_Wkts', 'bowler_Ave',
       'bowler_Econ', 'bowler_SR', 'bowler_4w', 'bowler_5w', 'bat_off_str_Ave',
       'bat_off_str_SR', 'bat_off_str_100', 'y_is_wicket_fallen',
       'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s', 'bat_off_str_6s',
       'bat_off_str_Mat', 'bat_off_str_Inns', 'bat_off_str_NO',
       'bat_off_str_Runs', 'bat_off_str_HS', 'bat_off_str_BF', 'date'],
      dtype='object')

In [16]:
df_matches = df_matches[['date','over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings','target', 'req_run_rate',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs','y_is_wicket_fallen', 'match_num',]]

df_matches

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
0,2015-11-26,0,0,0,0,0,0,0,0,0,...,0.000000,0,0,0,0,0,0,5,0,468
1,2015-11-26,0,0,0,0,0,3,3,1,4,...,5.000000,5,0,1,1,0,2,11,1,468
2,2015-11-26,6,0,5,1,0,0,6,0,6,...,8.000000,16,1,2,1,0,0,2,1,468
3,2015-11-26,7,1,11,0,0,3,0,0,0,...,6.000000,18,2,3,1,0,0,1,1,468
4,2015-11-26,12,1,7,0,0,1,2,0,0,...,4.750000,19,3,4,0,0,1,6,0,468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,6,0,19,5,0,19,36,20,46,...,8.916667,107,1,12,1,0,1,7,1,665
19106,2018-04-03,12,1,15,0,0,20,1,21,1,...,8.769231,114,2,13,0,0,0,6,0,665
19107,2018-04-03,12,1,26,2,0,6,21,2,22,...,8.571429,120,2,14,0,0,1,12,0,665
19108,2018-04-03,18,1,21,1,0,24,11,26,8,...,8.800000,132,2,15,0,0,0,7,0,665
19109,2018-04-03,12,0,22,1,0,26,15,27,14,...,8.687500,139,2,16,0,1,2,15,0,665

In [17]:
# Filter the DataFrame for values greater than a specific date
specific_date = pd.to_datetime('2018-01-01')
df_matches = df_matches[df_matches['date'] > specific_date]

In [18]:
#Getting the total matches
# Get the unique values in the 'column_name' column
match_list = df_matches['match_num'].unique()

# Display the unique values
print(len(match_list))

319

In [19]:
df_matches.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'target', 'req_run_rate', 'over_start_run_rate',
       'over_start_total_score', 'over_start_total_wickets_fallen', 'over',
       'wickets_fallen', 'sixers', 'fours', 'total_runs', 'y_is_wicket_fallen',
       'match_num'],
      dtype='object')

In [20]:
## Select Data for Training

In [21]:
df_final = df_matches[['date','over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings','over_start_run_rate',
       'over_start_total_score','over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs','y_is_wicket_fallen','match_num']]

In [22]:
df_final

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
40,2021-10-24,0,0,0,0,0,0,0,0,0,...,0.000000,0,0,0,1,0,0,2,1,1361
41,2021-10-24,0,0,0,0,0,3,2,1,1,...,2.000000,2,1,1,0,0,0,4,0,1361
42,2021-10-24,6,1,2,0,0,4,7,3,3,...,3.000000,6,1,2,1,1,0,8,1,1361
43,2021-10-24,6,0,4,0,0,4,5,7,4,...,4.666667,14,2,3,0,0,1,7,0,1361
44,2021-10-24,12,2,10,0,0,6,9,11,6,...,5.250000,21,2,4,0,1,0,9,0,1361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,6,0,19,5,0,19,36,20,46,...,8.916667,107,1,12,1,0,1,7,1,665
19106,2018-04-03,12,1,15,0,0,20,1,21,1,...,8.769231,114,2,13,0,0,0,6,0,665
19107,2018-04-03,12,1,26,2,0,6,21,2,22,...,8.571429,120,2,14,0,0,1,12,0,665
19108,2018-04-03,18,1,21,1,0,24,11,26,8,...,8.800000,132,2,15,0,0,0,7,0,665
19109,2018-04-03,12,0,22,1,0,26,15,27,14,...,8.687500,139,2,16,0,1,2,15,0,665

In [23]:
df_final.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'wickets_fallen', 'sixers',
       'fours', 'total_runs', 'y_is_wicket_fallen', 'match_num'],
      dtype='object')

In [24]:
cols_to_scale = ['over_start_bowler_balls_bowled', 'over_start_bowler_wickets_taken',
       'over_start_bowler_runs_given', 'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs',]

In [53]:
train_test_Date = pd.to_datetime('2022-08-01')
filtered_df = df_final[df_final['date'] > train_test_Date]
filtered_df

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
3486,2022-08-02,0,0,0,0,0,0,0,0,0,...,0.000000,0,0,0,0,0,0,1,0,1720
3487,2022-08-02,0,0,0,0,0,4,2,0,1,...,1.000000,1,0,1,0,0,1,6,0,1720
3488,2022-08-02,0,0,0,0,0,8,4,7,0,...,3.500000,7,0,2,0,1,1,15,0,1720
3489,2022-08-02,6,0,6,1,1,9,9,9,13,...,7.333333,22,0,3,0,0,2,10,0,1720
3490,2022-08-02,0,0,0,1,0,15,9,23,9,...,8.000000,32,0,4,0,1,0,9,0,1720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,9,0,15,0,0,7,3,5,4,...,8.416667,101,5,12,1,0,1,6,1,1986
5913,2023-01-07,13,2,15,0,0,0,8,0,6,...,8.230769,107,6,13,0,2,0,15,0,1986
5914,2023-01-07,20,1,27,0,2,0,14,0,21,...,8.714286,122,6,14,1,0,0,3,1,1986
5915,2023-01-07,15,1,21,0,2,3,15,2,22,...,8.333333,125,7,15,1,0,2,10,1,1986
5916,2023-01-07,16,1,18,0,2,3,16,8,23,...,8.437500,135,8,16,2,0,0,2,1,1986

In [54]:
from sklearn.model_selection import train_test_split
X_train = df_final[df_final['date'] <= train_test_Date]

In [55]:
test_Date = pd.to_datetime('2022-08-01')
X_test  =  df_final[df_final['date'] > test_Date]
X_test

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
3486,2022-08-02,0,0,0,0,0,0,0,0,0,...,0.000000,0,0,0,0,0,0,1,0,1720
3487,2022-08-02,0,0,0,0,0,4,2,0,1,...,1.000000,1,0,1,0,0,1,6,0,1720
3488,2022-08-02,0,0,0,0,0,8,4,7,0,...,3.500000,7,0,2,0,1,1,15,0,1720
3489,2022-08-02,6,0,6,1,1,9,9,9,13,...,7.333333,22,0,3,0,0,2,10,0,1720
3490,2022-08-02,0,0,0,1,0,15,9,23,9,...,8.000000,32,0,4,0,1,0,9,0,1720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,9,0,15,0,0,7,3,5,4,...,8.416667,101,5,12,1,0,1,6,1,1986
5913,2023-01-07,13,2,15,0,0,0,8,0,6,...,8.230769,107,6,13,0,2,0,15,0,1986
5914,2023-01-07,20,1,27,0,2,0,14,0,21,...,8.714286,122,6,14,1,0,0,3,1,1986
5915,2023-01-07,15,1,21,0,2,3,15,2,22,...,8.333333,125,7,15,1,0,2,10,1,1986
5916,2023-01-07,16,1,18,0,2,3,16,8,23,...,8.437500,135,8,16,2,0,0,2,1,1986

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\4151951648.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

In [57]:
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

C:\Users\Arul\AppData\Local\Temp\ipykernel_20168\2855813504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

In [58]:
X_train['match_num']

40       1361
41       1361
42       1361
43       1361
44       1361
         ...
19105     665
19106     665
19107     665
19108     665
19109     665
Name: match_num, Length: 9802, dtype: int64

In [59]:
match_list

array([1361, 1374, 1381, 1377, 1390, 1392, 1391, 1398, 1400, 1402, 1415,
       1420, 1428, 1434, 1440, 1443,  654, 1110, 1448, 1450, 1456, 1457,
       1174, 1179, 1208, 1366, 1454, 1379, 1375, 1216, 1176, 1455, 1384,
       1439, 1191, 1265, 1260, 1193, 1453, 1378, 1367, 1188, 1185, 1195,
       1178, 1369, 1192,  667, 1382, 1218, 1189, 1168, 1273, 1447, 1354,
       1222, 1446, 1458, 1449, 1351, 1357, 1467, 1466, 1470, 1473, 1492,
       1478, 1479, 1493, 1494, 1495, 1496, 1504, 1551, 1552, 1554, 1564,
       1569, 1571, 1572, 1607,  846, 1631, 1617, 1616, 1628, 1702, 1716,
       1698, 1693, 1720, 1718, 1725, 1726, 1728, 1732, 1735, 1750, 1753,
       1748, 1755, 1757, 1758, 1761, 1759, 1769, 1764, 1760, 1789, 1788,
       1795, 1794, 1798, 1793, 1796, 1803, 1801, 1804, 1802, 1800, 1806,
       1805, 1818, 1817, 1808, 1807, 1816, 1812, 1819, 1815, 1811, 1809,
       1850, 1845, 1840, 1842, 1839, 1847, 1858, 1853, 1856, 1860, 1861,
       1864, 1872, 1867, 1877, 1878, 1879, 1898, 1984, 1985, 1986,  669,
        883, 1009, 1148, 1206, 1258, 1243,  749,  686, 1031, 1119,  690,
        650,  763, 1146,  664, 1129,  659, 1000, 1032, 1116,  653,  649,
       1075,  716, 1039, 1118, 1002,  705,  714, 1115,  993,  693,  880,
        647, 1113, 1190, 1251,  892, 1033, 1008, 1126, 1128, 1078,  712,
        661,  657,  639,  922, 1207, 1139,  703, 1014,  702, 1114, 1140,
       1096,  655, 1131, 1121,  718,  692, 1141,  684,  842,  735, 1020,
        658,  706,  689,  688, 1111, 1046, 1212, 1263, 1109,  893, 1165,
        645,  711, 1123,  646,  772, 1127, 1132,  701,  843,  708, 1138,
       1145, 1015, 1120, 1135,  707,  710,  660, 1022,  732,  709,  748,
        914, 1181,  978,  668, 1124,  738,  682,  704,  638,  750, 1204,
        679,  641,  715, 1024,  925,  734,  992, 1094, 1043,  663,  640,
       1097, 1017, 1147, 1001,  717, 1133,  736,  648, 1026, 1095, 1041,
       1117, 1007,  998, 1125,  662,  888,  878, 1122,  695,  758,  651,
       1093,  652, 1270,  751, 1065,  752,  642, 1108, 1180, 1027, 1210,
       1130, 1037,  694, 1016,  988,  737,  879, 1052,  656, 1034,  665],
      dtype=int64)

In [60]:
X_train.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'wickets_fallen', 'sixers',
       'fours', 'total_runs', 'y_is_wicket_fallen', 'match_num'],
      dtype='object')

In [61]:
train_cols = ['over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'over_start_run_rate', 'over_start_total_score', 
       'over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs']

In [62]:
X_train

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
40,2021-10-24,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-1.042091,-1.110239,-0.877736,-0.932807,...,-2.640386,-1.458700,-1.161842,-1.620460,1.221903,-0.519468,-0.818309,-1.323982,1,1361
41,2021-10-24,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.786324,-0.942167,-0.819911,-0.875120,...,-1.899894,-1.417309,-0.687662,-1.443174,-0.586779,-0.519468,-0.818309,-0.890359,0,1361
42,2021-10-24,-0.303001,0.972602,-0.795359,-0.756899,-0.503743,-0.701068,-0.521988,-0.704260,-0.759748,...,-1.529648,-1.334528,-0.687662,-1.265888,1.221903,1.149983,-0.818309,-0.023114,1,1361
43,2021-10-24,-0.303001,-0.557892,-0.584059,-0.756899,-0.503743,-0.701068,-0.690060,-0.472960,-0.702062,...,-0.912571,-1.168965,-0.213482,-1.088603,-0.586779,-0.519468,0.449242,-0.239926,0,1361
44,2021-10-24,0.583659,2.503095,0.049839,-0.756899,-0.503743,-0.530557,-0.353916,-0.241660,-0.586690,...,-0.696594,-1.024098,-0.213482,-0.911317,-0.586779,1.149983,-0.818309,0.193697,0,1361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,-0.303001,-0.557892,1.000687,1.880355,-0.503743,0.577768,1.915053,0.278766,1.720756,...,0.660974,0.755700,-0.687662,0.506970,1.221903,-0.519468,0.449242,-0.239926,1,665
19106,2018-04-03,0.583659,0.972602,0.578088,-0.756899,-0.503743,0.663024,-1.026203,0.336591,-0.875120,...,0.606386,0.900568,-0.213482,0.684256,-0.586779,-0.519468,-0.818309,-0.456737,0,665
19107,2018-04-03,0.583659,0.972602,1.740235,0.298003,-0.503743,-0.530557,0.654514,-0.762086,0.336289,...,0.533151,1.024740,-0.213482,0.861542,-0.586779,-0.519468,0.449242,0.844131,0,665
19108,2018-04-03,1.470320,0.972602,1.211986,-0.229448,-0.503743,1.004047,-0.185844,0.625717,-0.471317,...,0.617779,1.273084,-0.213482,1.038828,-0.586779,-0.519468,-0.818309,-0.239926,0,665
19109,2018-04-03,0.583659,-0.557892,1.317636,-0.229448,-0.503743,1.174558,0.150299,0.683542,-0.125200,...,0.576126,1.417951,-0.213482,1.216114,-0.586779,1.149983,1.716794,1.494564,0,665

In [63]:
o = 5
X_train[(X_train['match_num'] == 1456) & (X_train['innings'] == 1)].reset_index(drop=True).loc[o-5:o, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen']

,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,innings,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen
0,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-1.042091,-1.110239,-0.877736,-0.932807,1,-2.640386,-1.458700,-1.161842,-1.620460,-0.586779,-0.519468,0.449242,-0.239926,0
1,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.871580,-0.774095,-0.646435,-0.759748,1,-0.048664,-1.313832,-1.161842,-1.443174,1.221903,-0.519468,-0.818309,-1.540793,1
2,-0.303001,-0.557892,-0.267110,-0.756899,-0.503743,-1.042091,-0.437952,-0.877736,-0.702062,1,-1.159402,-1.293137,-0.687662,-1.265888,-0.586779,-0.519468,0.449242,-0.673548,0
3,-0.303001,0.972602,-0.901008,-0.229448,-0.503743,-0.871580,-0.101808,-0.877736,-0.413631,1,-1.035987,-1.189660,-0.687662,-1.088603,-0.586779,-0.519468,-0.818309,-1.323982,0
4,0.583659,-0.557892,0.261139,-0.756899,-0.503743,0.492512,-0.942167,-0.241660,-0.932807,1,-1.251963,-1.148270,-0.687662,-0.911317,-0.586779,1.149983,1.716794,1.928187,0
5,-1.189662,-0.557892,-1.006658,-0.229448,-0.503743,0.833535,-0.774095,0.452242,-0.644376,1,-0.270812,-0.796449,-0.687662,-0.734031,-0.586779,1.149983,0.449242,1.060942,0

In [64]:
X_train_rnn = []
y_train_rnn = []

#Tracking down 5 previous overs

for match in match_list:
    print("In new Match" , match)
    for i in range(1,3):
        print("In new Innings" , i)
        innings_df = X_train[(X_train['match_num'] == match) & (X_train['innings'] == i)]
        print(len(innings_df))
        
        for over in range(5,len(innings_df)):
            
            X_train_rnn.append(innings_df.reset_index(drop=True).loc[over-5:over-1, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen'])
            y_train_rnn.append(innings_df.reset_index(drop=True).loc[over, 'y_is_wicket_fallen'])

In new Match 1361
In new Innings 1
20
In new Innings 2
18
In new Match 1374
In new Innings 1
20
In new Innings 2
17
In new Match 1381
In new Innings 1
20
In new Innings 2
15
In new Match 1377
In new Innings 1
20
In new Innings 2
19
In new Match 1390
In new Innings 1
20
In new Innings 2
20
In new Match 1392
In new Innings 1
20
In new Innings 2
20
In new Match 1391
In new Innings 1
15
In new Innings 2
7
In new Match 1398
In new Innings 1
20
In new Innings 2
17
In new Match 1400
In new Innings 1
20
In new Innings 2
20
In new Match 1402
In new Innings 1
20
In new Innings 2
19
In new Match 1415
In new Innings 1
20
In new Innings 2
19
In new Match 1420
In new Innings 1
20
In new Innings 2
19
In new Match 1428
In new Innings 1
20
In new Innings 2
19
In new Match 1434
In new Innings 1
20
In new Innings 2
20
In new Match 1440
In new Innings 1
20
In new Innings 2
18
In new Match 1443
In new Innings 1
20
In new Innings 2
19
In new Match 654
In new Innings 1
20
In new Innings 2
19
In new Match 1110
In new Innings 1
20
In new Innings 2
20
In new Match 1448
In new Innings 1
20
In new Innings 2
19
In new Match 1450
In new Innings 1
20
In new Innings 2
19
In new Match 1456
In new Innings 1
20
In new Innings 2
20
In new Match 1457
In new Innings 1
20
In new Innings 2
20
In new Match 1174
In new Innings 1
20
In new Innings 2
19
In new Match 1179
In new Innings 1
20
In new Innings 2
20
In new Match 1208
In new Innings 1
20
In new Innings 2
20
In new Match 1366
In new Innings 1
20
In new Innings 2
19
In new Match 1454
In new Innings 1
20
In new Innings 2
20
In new Match 1379
In new Innings 1
20
In new Innings 2
12
In new Match 1375
In new Innings 1
20
In new Innings 2
20
In new Match 1216
In new Innings 1
20
In new Innings 2
20
In new Match 1176
In new Innings 1
20
In new Innings 2
15
In new Match 1455
In new Innings 1
20
In new Innings 2
20
In new Match 1384
In new Innings 1
19
In new Innings 2
14
In new Match 1439
In new Innings 1
20
In new Innings 2
20
In new Match 1191
In new Innings 1
20
In new Innings 2
20
In new Match 1265
In new Innings 1
20
In new Innings 2
20
In new Match 1260
In new Innings 1
20
In new Innings 2
20
In new Match 1193
In new Innings 1
20
In new Innings 2
20
In new Match 1453
In new Innings 1
20
In new Innings 2
18
In new Match 1378
In new Innings 1
20
In new Innings 2
20
In new Match 1367
In new Innings 1
20
In new Innings 2
19
In new Match 1188
In new Innings 1
20
In new Innings 2
20
In new Match 1185
In new Innings 1
20
In new Innings 2
16
In new Match 1195
In new Innings 1
20
In new Innings 2
20
In new Match 1178
In new Innings 1
20
In new Innings 2
20
In new Match 1369
In new Innings 1
20
In new Innings 2
15
In new Match 1192
In new Innings 1
20
In new Innings 2
20
In new Match 667
In new Innings 1
20
In new Innings 2
19
In new Match 1382
In new Innings 1
20
In new Innings 2
19
In new Match 1218
In new Innings 1
20
In new Innings 2
19
In new Match 1189
In new Innings 1
20
In new Innings 2
15
In new Match 1168
In new Innings 1
20
In new Innings 2
17
In new Match 1273
In new Innings 1
20
In new Innings 2
15
In new Match 1447
In new Innings 1
20
In new Innings 2
20
In new Match 1354
In new Innings 1
15
In new Innings 2
9
In new Match 1222
In new Innings 1
20
In new Innings 2
14
In new Match 1446
In new Innings 1
20
In new Innings 2
18
In new Match 1458
In new Innings 1
20
In new Innings 2
19
In new Match 1449
In new Innings 1
20
In new Innings 2
20
In new Match 1351
In new Innings 1
20
In new Innings 2
20
In new Match 1357
In new Innings 1
20
In new Innings 2
19
In new Match 1467
In new Innings 1
20
In new Innings 2
19
In new Match 1466
In new Innings 1
20
In new Innings 2
17
In new Match 1470
In new Innings 1
20
In new Innings 2
19
In new Match 1473
In new Innings 1
20
In new Innings 2
20
In new Match 1492
In new Innings 1
20
In new Innings 2
20
In new Match 1478
In new Innings 1
20
In new Innings 2
20
In new Match 1479
In new Innings 1
20
In new Innings 2
20
In new Match 1493
In new Innings 1
20
In new Innings 2
18
In new Match 1494
In new Innings 1
20
In new Innings 2
17
In new Match 1495
In new Innings 1
20
In new Innings 2
18
In new Match 1496
In new Innings 1
20
In new Innings 2
18
In new Match 1504
In new Innings 1
20
In new Innings 2
20
In new Match 1551
In new Innings 1
20
In new Innings 2
14
In new Match 1552
In new Innings 1
20
In new Innings 2
18
In new Match 1554
In new Innings 1
20
In new Innings 2
20
In new Match 1564
In new Innings 1
20
In new Innings 2
20
In new Match 1569
In new Innings 1
20
In new Innings 2
19
In new Match 1571
In new Innings 1
20
In new Innings 2
20
In new Match 1572
In new Innings 1
20
In new Innings 2
17
In new Match 1607
In new Innings 1
20
In new Innings 2
20
In new Match 846
In new Innings 1
20
In new Innings 2
20
In new Match 1631
In new Innings 1
20
In new Innings 2
20
In new Match 1617
In new Innings 1
20
In new Innings 2
19
In new Match 1616
In new Innings 1
20
In new Innings 2
20
In new Match 1628
In new Innings 1
20
In new Innings 2
17
In new Match 1702
In new Innings 1
20
In new Innings 2
20
In new Match 1716
In new Innings 1
20
In new Innings 2
17
In new Match 1698
In new Innings 1
20
In new Innings 2
17
In new Match 1693
In new Innings 1
20
In new Innings 2
20
In new Match 1720
In new Innings 1
0
In new Innings 2
0
In new Match 1718
In new Innings 1
20
In new Innings 2
20
In new Match 1725
In new Innings 1
0
In new Innings 2
0
In new Match 1726
In new Innings 1
0
In new Innings 2
0
In new Match 1728
In new Innings 1
0
In new Innings 2
0
In new Match 1732
In new Innings 1
0
In new Innings 2
0
In new Match 1735
In new Innings 1
0
In new Innings 2
0
In new Match 1750
In new Innings 1
0
In new Innings 2
0
In new Match 1753
In new Innings 1
0
In new Innings 2
0
In new Match 1748
In new Innings 1
0
In new Innings 2
0
In new Match 1755
In new Innings 1
0
In new Innings 2
0
In new Match 1757
In new Innings 1
0
In new Innings 2
0
In new Match 1758
In new Innings 1
0
In new Innings 2
0
In new Match 1761
In new Innings 1
0
In new Innings 2
0
In new Match 1759
In new Innings 1
0
In new Innings 2
0
In new Match 1769
In new Innings 1
0
In new Innings 2
0
In new Match 1764
In new Innings 1
0
In new Innings 2
0
In new Match 1760
In new Innings 1
0
In new Innings 2
0
In new Match 1789
In new Innings 1
0
In new Innings 2
0
In new Match 1788
In new Innings 1
0
In new Innings 2
0
In new Match 1795
In new Innings 1
0
In new Innings 2
0
In new Match 1794
In new Innings 1
0
In new Innings 2
0
In new Match 1798
In new Innings 1
0
In new Innings 2
0
In new Match 1793
In new Innings 1
0
In new Innings 2
0
In new Match 1796
In new Innings 1
0
In new Innings 2
0
In new Match 1803
In new Innings 1
0
In new Innings 2
0
In new Match 1801
In new Innings 1
0
In new Innings 2
0
In new Match 1804
In new Innings 1
0
In new Innings 2
0
In new Match 1802
In new Innings 1
0
In new Innings 2
0
In new Match 1800
In new Innings 1
0
In new Innings 2
0
In new Match 1806
In new Innings 1
0
In new Innings 2
0
In new Match 1805
In new Innings 1
0
In new Innings 2
0
In new Match 1818
In new Innings 1
0
In new Innings 2
0
In new Match 1817
In new Innings 1
0
In new Innings 2
0
In new Match 1808
In new Innings 1
0
In new Innings 2
0
In new Match 1807
In new Innings 1
0
In new Innings 2
0
In new Match 1816
In new Innings 1
0
In new Innings 2
0
In new Match 1812
In new Innings 1
0
In new Innings 2
0
In new Match 1819
In new Innings 1
0
In new Innings 2
0
In new Match 1815
In new Innings 1
0
In new Innings 2
0
In new Match 1811
In new Innings 1
0
In new Innings 2
0
In new Match 1809
In new Innings 1
0
In new Innings 2
0
In new Match 1850
In new Innings 1
0
In new Innings 2
0
In new Match 1845
In new Innings 1
0
In new Innings 2
0
In new Match 1840
In new Innings 1
0
In new Innings 2
0
In new Match 1842
In new Innings 1
0
In new Innings 2
0
In new Match 1839
In new Innings 1
0
In new Innings 2
0
In new Match 1847
In new Innings 1
0
In new Innings 2
0
In new Match 1858
In new Innings 1
0
In new Innings 2
0
In new Match 1853
In new Innings 1
0
In new Innings 2
0
In new Match 1856
In new Innings 1
0
In new Innings 2
0
In new Match 1860
In new Innings 1
0
In new Innings 2
0
In new Match 1861
In new Innings 1
0
In new Innings 2
0
In new Match 1864
In new Innings 1
0
In new Innings 2
0
In new Match 1872
In new Innings 1
0
In new Innings 2
0
In new Match 1867
In new Innings 1
0
In new Innings 2
0
In new Match 1877
In new Innings 1
0
In new Innings 2
0
In new Match 1878
In new Innings 1
0
In new Innings 2
0
In new Match 1879
In new Innings 1
0
In new Innings 2
0
In new Match 1898
In new Innings 1
0
In new Innings 2
0
In new Match 1984
In new Innings 1
0
In new Innings 2
0
In new Match 1985
In new Innings 1
0
In new Innings 2
0
In new Match 1986
In new Innings 1
0
In new Innings 2
0
In new Match 669
In new Innings 1
20
In new Innings 2
20
In new Match 883
In new Innings 1
20
In new Innings 2
20
In new Match 1009
In new Innings 1
20
In new Innings 2
12
In new Match 1148
In new Innings 1
20
In new Innings 2
20
In new Match 1206
In new Innings 1
20
In new Innings 2
20
In new Match 1258
In new Innings 1
20
In new Innings 2
20
In new Match 1243
In new Innings 1
17
In new Innings 2
15
In new Match 749
In new Innings 1
20
In new Innings 2
20
In new Match 686
In new Innings 1
20
In new Innings 2
20
In new Match 1031
In new Innings 1
20
In new Innings 2
19
In new Match 1119
In new Innings 1
20
In new Innings 2
20
In new Match 690
In new Innings 1
20
In new Innings 2
19
In new Match 650
In new Innings 1
20
In new Innings 2
20
In new Match 763
In new Innings 1
20
In new Innings 2
16
In new Match 1146
In new Innings 1
20
In new Innings 2
14
In new Match 664
In new Innings 1
20
In new Innings 2
20
In new Match 1129
In new Innings 1
20
In new Innings 2
16
In new Match 659
In new Innings 1
19
In new Innings 2
18
In new Match 1000
In new Innings 1
20
In new Innings 2
20
In new Match 1032
In new Innings 1
20
In new Innings 2
20
In new Match 1116
In new Innings 1
20
In new Innings 2
20
In new Match 653
In new Innings 1
20
In new Innings 2
15
In new Match 649
In new Innings 1
20
In new Innings 2
19
In new Match 1075
In new Innings 1
20
In new Innings 2
20
In new Match 716
In new Innings 1
20
In new Innings 2
20
In new Match 1039
In new Innings 1
20
In new Innings 2
20
In new Match 1118
In new Innings 1
20
In new Innings 2
20
In new Match 1002
In new Innings 1
20
In new Innings 2
19
In new Match 705
In new Innings 1
20
In new Innings 2
20
In new Match 714
In new Innings 1
20
In new Innings 2
20
In new Match 1115
In new Innings 1
20
In new Innings 2
20
In new Match 993
In new Innings 1
20
In new Innings 2
18
In new Match 693
In new Innings 1
20
In new Innings 2
20
In new Match 880
In new Innings 1
20
In new Innings 2
16
In new Match 647
In new Innings 1
20
In new Innings 2
20
In new Match 1113
In new Innings 1
20
In new Innings 2
18
In new Match 1190
In new Innings 1
20
In new Innings 2
20
In new Match 1251
In new Innings 1
20
In new Innings 2
20
In new Match 892
In new Innings 1
20
In new Innings 2
19
In new Match 1033
In new Innings 1
20
In new Innings 2
17
In new Match 1008
In new Innings 1
20
In new Innings 2
17
In new Match 1126
In new Innings 1
20
In new Innings 2
14
In new Match 1128
In new Innings 1
20
In new Innings 2
19
In new Match 1078
In new Innings 1
20
In new Innings 2
17
In new Match 712
In new Innings 1
17
In new Innings 2
17
In new Match 661
In new Innings 1
20
In new Innings 2
20
In new Match 657
In new Innings 1
20
In new Innings 2
19
In new Match 639
In new Innings 1
20
In new Innings 2
16
In new Match 922
In new Innings 1
20
In new Innings 2
19
In new Match 1207
In new Innings 1
20
In new Innings 2
15
In new Match 1139
In new Innings 1
20
In new Innings 2
20
In new Match 703
In new Innings 1
20
In new Innings 2
20
In new Match 1014
In new Innings 1
20
In new Innings 2
20
In new Match 702
In new Innings 1
20
In new Innings 2
20
In new Match 1114
In new Innings 1
20
In new Innings 2
20
In new Match 1140
In new Innings 1
18
In new Innings 2
16
In new Match 1096
In new Innings 1
20
In new Innings 2
19
In new Match 655
In new Innings 1
20
In new Innings 2
20
In new Match 1131
In new Innings 1
20
In new Innings 2
16
In new Match 1121
In new Innings 1
20
In new Innings 2
17
In new Match 718
In new Innings 1
20
In new Innings 2
17
In new Match 692
In new Innings 1
20
In new Innings 2
10
In new Match 1141
In new Innings 1
10
In new Innings 2
10
In new Match 684
In new Innings 1
20
In new Innings 2
19
In new Match 842
In new Innings 1
20
In new Innings 2
18
In new Match 735
In new Innings 1
20
In new Innings 2
20
In new Match 1020
In new Innings 1
20
In new Innings 2
19
In new Match 658
In new Innings 1
20
In new Innings 2
20
In new Match 706
In new Innings 1
20
In new Innings 2
20
In new Match 689
In new Innings 1
20
In new Innings 2
20
In new Match 688
In new Innings 1
20
In new Innings 2
20
In new Match 1111
In new Innings 1
20
In new Innings 2
20
In new Match 1046
In new Innings 1
20
In new Innings 2
15
In new Match 1212
In new Innings 1
20
In new Innings 2
19
In new Match 1263
In new Innings 1
20
In new Innings 2
20
In new Match 1109
In new Innings 1
20
In new Innings 2
20
In new Match 893
In new Innings 1
20
In new Innings 2
17
In new Match 1165
In new Innings 1
20
In new Innings 2
18
In new Match 645
In new Innings 1
20
In new Innings 2
19
In new Match 711
In new Innings 1
10
In new Innings 2
10
In new Match 1123
In new Innings 1
20
In new Innings 2
18
In new Match 646
In new Innings 1
20
In new Innings 2
15
In new Match 772
In new Innings 1
20
In new Innings 2
20
In new Match 1127
In new Innings 1
20
In new Innings 2
19
In new Match 1132
In new Innings 1
20
In new Innings 2
18
In new Match 701
In new Innings 1
20
In new Innings 2
17
In new Match 843
In new Innings 1
20
In new Innings 2
16
In new Match 708
In new Innings 1
20
In new Innings 2
17
In new Match 1138
In new Innings 1
20
In new Innings 2
20
In new Match 1145
In new Innings 1
20
In new Innings 2
20
In new Match 1015
In new Innings 1
20
In new Innings 2
20
In new Match 1120
In new Innings 1
20
In new Innings 2
20
In new Match 1135
In new Innings 1
20
In new Innings 2
20
In new Match 707
In new Innings 1
20
In new Innings 2
18
In new Match 710
In new Innings 1
20
In new Innings 2
20
In new Match 660
In new Innings 1
20
In new Innings 2
20
In new Match 1022
In new Innings 1
20
In new Innings 2
19
In new Match 732
In new Innings 1
20
In new Innings 2
20
In new Match 709
In new Innings 1
20
In new Innings 2
20
In new Match 748
In new Innings 1
20
In new Innings 2
20
In new Match 914
In new Innings 1
20
In new Innings 2
18
In new Match 1181
In new Innings 1
20
In new Innings 2
20
In new Match 978
In new Innings 1
20
In new Innings 2
20
In new Match 668
In new Innings 1
20
In new Innings 2
19
In new Match 1124
In new Innings 1
20
In new Innings 2
20
In new Match 738
In new Innings 1
20
In new Innings 2
20
In new Match 682
In new Innings 1
20
In new Innings 2
11
In new Match 704
In new Innings 1
20
In new Innings 2
20
In new Match 638
In new Innings 1
20
In new Innings 2
17
In new Match 750
In new Innings 1
20
In new Innings 2
19
In new Match 1204
In new Innings 1
20
In new Innings 2
19
In new Match 679
In new Innings 1
20
In new Innings 2
20
In new Match 641
In new Innings 1
20
In new Innings 2
20
In new Match 715
In new Innings 1
19
In new Innings 2
11
In new Match 1024
In new Innings 1
20
In new Innings 2
20
In new Match 925
In new Innings 1
20
In new Innings 2
20
In new Match 734
In new Innings 1
20
In new Innings 2
20
In new Match 992
In new Innings 1
20
In new Innings 2
19
In new Match 1094
In new Innings 1
20
In new Innings 2
20
In new Match 1043
In new Innings 1
20
In new Innings 2
20
In new Match 663
In new Innings 1
20
In new Innings 2
14
In new Match 640
In new Innings 1
20
In new Innings 2
19
In new Match 1097
In new Innings 1
20
In new Innings 2
20
In new Match 1017
In new Innings 1
20
In new Innings 2
20
In new Match 1147
In new Innings 1
20
In new Innings 2
18
In new Match 1001
In new Innings 1
20
In new Innings 2
20
In new Match 717
In new Innings 1
20
In new Innings 2
17
In new Match 1133
In new Innings 1
20
In new Innings 2
19
In new Match 736
In new Innings 1
20
In new Innings 2
20
In new Match 648
In new Innings 1
20
In new Innings 2
17
In new Match 1026
In new Innings 1
20
In new Innings 2
18
In new Match 1095
In new Innings 1
20
In new Innings 2
20
In new Match 1041
In new Innings 1
20
In new Innings 2
20
In new Match 1117
In new Innings 1
20
In new Innings 2
19
In new Match 1007
In new Innings 1
20
In new Innings 2
16
In new Match 998
In new Innings 1
20
In new Innings 2
20
In new Match 1125
In new Innings 1
20
In new Innings 2
18
In new Match 662
In new Innings 1
20
In new Innings 2
20
In new Match 888
In new Innings 1
20
In new Innings 2
19
In new Match 878
In new Innings 1
20
In new Innings 2
20
In new Match 1122
In new Innings 1
20
In new Innings 2
19
In new Match 695
In new Innings 1
17
In new Innings 2
16
In new Match 758
In new Innings 1
20
In new Innings 2
20
In new Match 651
In new Innings 1
20
In new Innings 2
19
In new Match 1093
In new Innings 1
20
In new Innings 2
20
In new Match 652
In new Innings 1
20
In new Innings 2
20
In new Match 1270
In new Innings 1
19
In new Innings 2
15
In new Match 751
In new Innings 1
20
In new Innings 2
12
In new Match 1065
In new Innings 1
20
In new Innings 2
16
In new Match 752
In new Innings 1
13
In new Innings 2
11
In new Match 642
In new Innings 1
20
In new Innings 2
12
In new Match 1108
In new Innings 1
16
In new Innings 2
16
In new Match 1180
In new Innings 1
20
In new Innings 2
20
In new Match 1027
In new Innings 1
20
In new Innings 2
16
In new Match 1210
In new Innings 1
20
In new Innings 2
20
In new Match 1130
In new Innings 1
20
In new Innings 2
19
In new Match 1037
In new Innings 1
20
In new Innings 2
20
In new Match 694
In new Innings 1
20
In new Innings 2
18
In new Match 1016
In new Innings 1
20
In new Innings 2
20
In new Match 988
In new Innings 1
19
In new Innings 2
14
In new Match 737
In new Innings 1
20
In new Innings 2
19
In new Match 879
In new Innings 1
20
In new Innings 2
20
In new Match 1052
In new Innings 1
20
In new Innings 2
20
In new Match 656
In new Innings 1
20
In new Innings 2
19
In new Match 1034
In new Innings 1
20
In new Innings 2
18
In new Match 665
In new Innings 1
20
In new Innings 2
17

In [65]:
X_train_rnn[0]

,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,innings,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen
0,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-1.042091,-1.110239,-0.877736,-0.932807,1,-2.640386,-1.458700,-1.161842,-1.620460,1.221903,-0.519468,-0.818309,-1.323982,1
1,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.786324,-0.942167,-0.819911,-0.875120,1,-1.899894,-1.417309,-0.687662,-1.443174,-0.586779,-0.519468,-0.818309,-0.890359,0
2,-0.303001,0.972602,-0.795359,-0.756899,-0.503743,-0.701068,-0.521988,-0.704260,-0.759748,1,-1.529648,-1.334528,-0.687662,-1.265888,1.221903,1.149983,-0.818309,-0.023114,1
3,-0.303001,-0.557892,-0.584059,-0.756899,-0.503743,-0.701068,-0.690060,-0.472960,-0.702062,1,-0.912571,-1.168965,-0.213482,-1.088603,-0.586779,-0.519468,0.449242,-0.239926,0
4,0.583659,2.503095,0.049839,-0.756899,-0.503743,-0.530557,-0.353916,-0.241660,-0.586690,1,-0.696594,-1.024098,-0.213482,-0.911317,-0.586779,1.149983,-0.818309,0.193697,0

In [66]:
X_train_rnn , y_train_rnn = np.array(X_train_rnn).astype('float32') , np.array(y_train_rnn).astype('float32')

In [67]:
X_train_rnn.shape

(7232, 5, 19)

In [68]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

# Initialising the RNN
regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train_rnn.shape[1], X_train_rnn.shape[2])))
regressor.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a third LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a fourth LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

# Adding the output layer
regressor.add(Dense(units = 1,activation='sigmoid'))

# Compiling the RNN
regressor.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [69]:
# Fitting the RNN to the Training set
regressor.fit(X_train_rnn, y_train_rnn, epochs = 100, batch_size = 32)

Epoch 1/100
226/226 [==============================] - 10s 11ms/step - loss: 0.6027 - accuracy: 0.7011
Epoch 2/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5955 - accuracy: 0.7038
Epoch 3/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5940 - accuracy: 0.7038
Epoch 4/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5930 - accuracy: 0.7033
Epoch 5/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5942 - accuracy: 0.7053
Epoch 6/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5926 - accuracy: 0.7042
Epoch 7/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5917 - accuracy: 0.7026
Epoch 8/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5926 - accuracy: 0.7037
Epoch 9/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5903 - accuracy: 0.7059
Epoch 10/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5895 - accuracy: 0.7075
Epoch 11/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5881 - accuracy: 0.7077
Epoch 12/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5873 - accuracy: 0.7088
Epoch 13/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5866 - accuracy: 0.7110
Epoch 14/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5839 - accuracy: 0.7139
Epoch 15/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5817 - accuracy: 0.7153
Epoch 16/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5804 - accuracy: 0.7142
Epoch 17/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5783 - accuracy: 0.7190
Epoch 18/100
226/226 [==============================] - 3s 13ms/step - loss: 0.5758 - accuracy: 0.7181
Epoch 19/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5726 - accuracy: 0.7250
Epoch 20/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5691 - accuracy: 0.7222
Epoch 21/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5644 - accuracy: 0.7269
Epoch 22/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5604 - accuracy: 0.7311
Epoch 23/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5546 - accuracy: 0.7329
Epoch 24/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5516 - accuracy: 0.7384
Epoch 25/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5483 - accuracy: 0.7391
Epoch 26/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5413 - accuracy: 0.7409
Epoch 27/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5331 - accuracy: 0.7465
Epoch 28/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5335 - accuracy: 0.7482
Epoch 29/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5234 - accuracy: 0.7540
Epoch 30/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5163 - accuracy: 0.7572
Epoch 31/100
226/226 [==============================] - 2s 11ms/step - loss: 0.5157 - accuracy: 0.7577
Epoch 32/100
226/226 [==============================] - 3s 12ms/step - loss: 0.5050 - accuracy: 0.7623
Epoch 33/100
226/226 [==============================] - 3s 11ms/step - loss: 0.5013 - accuracy: 0.7666
Epoch 34/100
226/226 [==============================] - 3s 12ms/step - loss: 0.4955 - accuracy: 0.7681
Epoch 35/100
226/226 [==============================] - 2s 11ms/step - loss: 0.4921 - accuracy: 0.7694
Epoch 36/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4843 - accuracy: 0.7743
Epoch 37/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4788 - accuracy: 0.7775
Epoch 38/100
226/226 [==============================] - 3s 12ms/step - loss: 0.4752 - accuracy: 0.7789
Epoch 39/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4625 - accuracy: 0.7847
Epoch 40/100
226/226 [==============================] - 3s 12ms/step - loss: 0.4630 - accuracy: 0.7860
Epoch 41/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4577 - accuracy: 0.7908
Epoch 42/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4483 - accuracy: 0.7951
Epoch 43/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4413 - accuracy: 0.7954
Epoch 44/100
226/226 [==============================] - 3s 13ms/step - loss: 0.4394 - accuracy: 0.7988
Epoch 45/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4275 - accuracy: 0.8086
Epoch 46/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4204 - accuracy: 0.8081
Epoch 47/100
226/226 [==============================] - 2s 11ms/step - loss: 0.4120 - accuracy: 0.8107
Epoch 48/100
226/226 [==============================] - 3s 11ms/step - loss: 0.4118 - accuracy: 0.8081
Epoch 49/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3987 - accuracy: 0.8169
Epoch 50/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3912 - accuracy: 0.8245
Epoch 51/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3895 - accuracy: 0.8238
Epoch 52/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3874 - accuracy: 0.8256
Epoch 53/100
226/226 [==============================] - 3s 12ms/step - loss: 0.3839 - accuracy: 0.8252
Epoch 54/100
226/226 [==============================] - 2s 11ms/step - loss: 0.3749 - accuracy: 0.8321
Epoch 55/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3731 - accuracy: 0.8339
Epoch 56/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3621 - accuracy: 0.8400
Epoch 57/100
226/226 [==============================] - 3s 12ms/step - loss: 0.3525 - accuracy: 0.8451
Epoch 58/100
226/226 [==============================] - 2s 11ms/step - loss: 0.3503 - accuracy: 0.8467
Epoch 59/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3446 - accuracy: 0.8480
Epoch 60/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3402 - accuracy: 0.8520
Epoch 61/100
226/226 [==============================] - 2s 11ms/step - loss: 0.3428 - accuracy: 0.8515
Epoch 62/100
226/226 [==============================] - 2s 11ms/step - loss: 0.3201 - accuracy: 0.8591
Epoch 63/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3254 - accuracy: 0.8588
Epoch 64/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3208 - accuracy: 0.8652
Epoch 65/100
226/226 [==============================] - 3s 12ms/step - loss: 0.3152 - accuracy: 0.8608
Epoch 66/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3081 - accuracy: 0.8664
Epoch 67/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2969 - accuracy: 0.8713
Epoch 68/100
226/226 [==============================] - 3s 11ms/step - loss: 0.3068 - accuracy: 0.8655
Epoch 69/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2911 - accuracy: 0.8732
Epoch 70/100
226/226 [==============================] - 2s 11ms/step - loss: 0.2884 - accuracy: 0.8753
Epoch 71/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2816 - accuracy: 0.8791
Epoch 72/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2813 - accuracy: 0.8808
Epoch 73/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2797 - accuracy: 0.8836
Epoch 74/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2672 - accuracy: 0.8821
Epoch 75/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2687 - accuracy: 0.8827
Epoch 76/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2684 - accuracy: 0.8840
Epoch 77/100
226/226 [==============================] - 2s 11ms/step - loss: 0.2602 - accuracy: 0.8912
Epoch 78/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2599 - accuracy: 0.8906
Epoch 79/100
226/226 [==============================] - 2s 11ms/step - loss: 0.2485 - accuracy: 0.8953
Epoch 80/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2529 - accuracy: 0.8938
Epoch 81/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2395 - accuracy: 0.9007
Epoch 82/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2411 - accuracy: 0.9009
Epoch 83/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2396 - accuracy: 0.8977
Epoch 84/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2273 - accuracy: 0.9050
Epoch 85/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2406 - accuracy: 0.9010
Epoch 86/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2254 - accuracy: 0.9049
Epoch 87/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2289 - accuracy: 0.9035
Epoch 88/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2135 - accuracy: 0.9090
Epoch 89/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2171 - accuracy: 0.9075
Epoch 90/100
226/226 [==============================] - 3s 15ms/step - loss: 0.2125 - accuracy: 0.9147
Epoch 91/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2178 - accuracy: 0.9097
Epoch 92/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2042 - accuracy: 0.9169
Epoch 93/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2125 - accuracy: 0.9126
Epoch 94/100
226/226 [==============================] - 3s 12ms/step - loss: 0.2013 - accuracy: 0.9172
Epoch 95/100
226/226 [==============================] - 3s 11ms/step - loss: 0.2027 - accuracy: 0.9176
Epoch 96/100
226/226 [==============================] - 3s 12ms/step - loss: 0.1966 - accuracy: 0.9151
Epoch 97/100
226/226 [==============================] - 2s 11ms/step - loss: 0.2020 - accuracy: 0.9159
Epoch 98/100
226/226 [==============================] - 3s 14ms/step - loss: 0.1872 - accuracy: 0.9241
Epoch 99/100
226/226 [==============================] - 3s 14ms/step - loss: 0.1852 - accuracy: 0.9235
Epoch 100/100
226/226 [==============================] - 3s 14ms/step - loss: 0.1849 - accuracy: 0.9263

In [70]:
X_test

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen,match_num
3486,2022-08-02,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-1.042091,-1.110239,-0.877736,-0.932807,...,-2.640386,-1.458700,-1.161842,-1.620460,-0.586779,-0.519468,-0.818309,-1.540793,0,1720
3487,2022-08-02,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.701068,-0.942167,-0.877736,-0.875120,...,-2.270140,-1.438004,-1.161842,-1.443174,-0.586779,-0.519468,0.449242,-0.456737,0,1720
3488,2022-08-02,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.360045,-0.774095,-0.472960,-0.932807,...,-1.344525,-1.313832,-1.161842,-1.265888,-0.586779,1.149983,0.449242,1.494564,0,1720
3489,2022-08-02,-0.303001,-0.557892,-0.372760,-0.229448,0.465191,-0.274789,-0.353916,-0.357310,-0.182887,...,0.074751,-1.003403,-1.161842,-1.088603,-0.586779,-0.519468,1.716794,0.410508,0,1720
3490,2022-08-02,-1.189662,-0.557892,-1.006658,-0.229448,-0.503743,0.236745,-0.353916,0.452242,-0.413631,...,0.321582,-0.796449,-1.161842,-0.911317,-0.586779,1.149983,-0.818309,0.193697,0,1720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,0.140329,-0.557892,0.578088,-0.756899,-0.503743,-0.445301,-0.858131,-0.588610,-0.702062,...,0.475851,0.631528,1.209057,0.506970,1.221903,-0.519468,0.449242,-0.456737,1,1986
5913,2023-01-07,0.731436,2.503095,0.578088,-0.756899,-0.503743,-1.042091,-0.437952,-0.877736,-0.586690,...,0.407023,0.755700,1.683236,0.684256,-0.586779,2.819434,-0.818309,1.494564,0,1986
5914,2023-01-07,1.765874,0.972602,1.845885,-0.756899,1.434125,-1.042091,0.066263,-0.877736,0.278603,...,0.586043,1.066130,1.683236,0.861542,1.221903,-0.519468,-0.818309,-1.107171,1,1986
5915,2023-01-07,1.026990,0.972602,1.211986,-0.756899,1.434125,-0.786324,0.150299,-0.762086,0.336289,...,0.444997,1.128216,2.157416,1.038828,1.221903,-0.519468,1.716794,0.410508,1,1986
5916,2023-01-07,1.174767,0.972602,0.895037,-0.756899,1.434125,-0.786324,0.234335,-0.415135,0.393975,...,0.483564,1.335170,2.631596,1.216114,3.030586,-0.519468,-0.818309,-1.323982,1,1986

In [71]:
## Testing Mechanism 
test_match_list = X_test['match_num'].unique()
test_match_list

array([1720, 1725, 1726, 1728, 1732, 1735, 1750, 1753, 1748, 1755, 1757,
       1758, 1761, 1759, 1769, 1764, 1760, 1789, 1788, 1795, 1794, 1798,
       1793, 1796, 1803, 1801, 1804, 1802, 1800, 1806, 1805, 1818, 1817,
       1808, 1807, 1816, 1812, 1819, 1815, 1811, 1809, 1850, 1845, 1840,
       1842, 1839, 1847, 1858, 1853, 1856, 1860, 1861, 1864, 1872, 1867,
       1877, 1878, 1879, 1898, 1984, 1985, 1986], dtype=int64)

In [72]:
X_test_rnn = []
y_test_rnn = []

#Tracking down 5 previous overs

for match in test_match_list:
    print("In new Match" , match)
    for i in range(1,3):
        print("In new Innings" , i)
        innings_df = X_test[(X_test['match_num'] == match) & (X_test['innings'] == i)]
        print(len(innings_df))
        
        for over in range(5,len(innings_df)):
            
            X_test_rnn.append(innings_df.reset_index(drop=True).loc[over-5:over-1, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen'])
            y_test_rnn.append(innings_df.reset_index(drop=True).loc[over, 'y_is_wicket_fallen'])

In new Match 1720
In new Innings 1
20
In new Innings 2
19
In new Match 1725
In new Innings 1
20
In new Innings 2
20
In new Match 1726
In new Innings 1
20
In new Innings 2
16
In new Match 1728
In new Innings 1
20
In new Innings 2
20
In new Match 1732
In new Innings 1
20
In new Innings 2
20
In new Match 1735
In new Innings 1
20
In new Innings 2
19
In new Match 1750
In new Innings 1
20
In new Innings 2
20
In new Match 1753
In new Innings 1
20
In new Innings 2
19
In new Match 1748
In new Innings 1
20
In new Innings 2
11
In new Match 1755
In new Innings 1
20
In new Innings 2
20
In new Match 1757
In new Innings 1
20
In new Innings 2
20
In new Match 1758
In new Innings 1
20
In new Innings 2
20
In new Match 1761
In new Innings 1
20
In new Innings 2
20
In new Match 1759
In new Innings 1
20
In new Innings 2
20
In new Match 1769
In new Innings 1
20
In new Innings 2
20
In new Match 1764
In new Innings 1
20
In new Innings 2
17
In new Match 1760
In new Innings 1
20
In new Innings 2
20
In new Match 1789
In new Innings 1
20
In new Innings 2
20
In new Match 1788
In new Innings 1
20
In new Innings 2
20
In new Match 1795
In new Innings 1
20
In new Innings 2
20
In new Match 1794
In new Innings 1
8
In new Innings 2
8
In new Match 1798
In new Innings 1
20
In new Innings 2
20
In new Match 1793
In new Innings 1
20
In new Innings 2
20
In new Match 1796
In new Innings 1
20
In new Innings 2
20
In new Match 1803
In new Innings 1
20
In new Innings 2
20
In new Match 1801
In new Innings 1
19
In new Innings 2
20
In new Match 1804
In new Innings 1
20
In new Innings 2
20
In new Match 1802
In new Innings 1
20
In new Innings 2
15
In new Match 1800
In new Innings 1
20
In new Innings 2
17
In new Match 1806
In new Innings 1
20
In new Innings 2
20
In new Match 1805
In new Innings 1
20
In new Innings 2
19
In new Match 1818
In new Innings 1
20
In new Innings 2
20
In new Match 1817
In new Innings 1
20
In new Innings 2
20
In new Match 1808
In new Innings 1
20
In new Innings 2
20
In new Match 1807
In new Innings 1
20
In new Innings 2
20
In new Match 1816
In new Innings 1
20
In new Innings 2
20
In new Match 1812
In new Innings 1
20
In new Innings 2
20
In new Match 1819
In new Innings 1
20
In new Innings 2
20
In new Match 1815
In new Innings 1
20
In new Innings 2
17
In new Match 1811
In new Innings 1
20
In new Innings 2
18
In new Match 1809
In new Innings 1
20
In new Innings 2
19
In new Match 1850
In new Innings 1
20
In new Innings 2
20
In new Match 1845
In new Innings 1
20
In new Innings 2
17
In new Match 1840
In new Innings 1
20
In new Innings 2
19
In new Match 1842
In new Innings 1
20
In new Innings 2
20
In new Match 1839
In new Innings 1
20
In new Innings 2
18
In new Match 1847
In new Innings 1
20
In new Innings 2
17
In new Match 1858
In new Innings 1
20
In new Innings 2
20
In new Match 1853
In new Innings 1
20
In new Innings 2
20
In new Match 1856
In new Innings 1
20
In new Innings 2
19
In new Match 1860
In new Innings 1
20
In new Innings 2
16
In new Match 1861
In new Innings 1
20
In new Innings 2
14
In new Match 1864
In new Innings 1
20
In new Innings 2
20
In new Match 1872
In new Innings 1
20
In new Innings 2
19
In new Match 1867
In new Innings 1
20
In new Innings 2
20
In new Match 1877
In new Innings 1
20
In new Innings 2
20
In new Match 1878
In new Innings 1
20
In new Innings 2
16
In new Match 1879
In new Innings 1
20
In new Innings 2
19
In new Match 1898
In new Innings 1
20
In new Innings 2
19
In new Match 1984
In new Innings 1
20
In new Innings 2
20
In new Match 1985
In new Innings 1
20
In new Innings 2
20
In new Match 1986
In new Innings 1
20
In new Innings 2
17

In [73]:
X_test_rnn[2]

,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,innings,over_start_run_rate,over_start_total_score,over_start_total_wickets_fallen,over,wickets_fallen,sixers,fours,total_runs,y_is_wicket_fallen
2,-1.189662,-0.557892,-1.006658,-0.756899,-0.503743,-0.360045,-0.774095,-0.472960,-0.932807,1,-1.344525,-1.313832,-1.161842,-1.265888,-0.586779,1.149983,0.449242,1.494564,0
3,-0.303001,-0.557892,-0.372760,-0.229448,0.465191,-0.274789,-0.353916,-0.357310,-0.182887,1,0.074751,-1.003403,-1.161842,-1.088603,-0.586779,-0.519468,1.716794,0.410508,0
4,-1.189662,-0.557892,-1.006658,-0.229448,-0.503743,0.236745,-0.353916,0.452242,-0.413631,1,0.321582,-0.796449,-1.161842,-0.911317,-0.586779,1.149983,-0.818309,0.193697,0
5,-1.189662,-0.557892,-1.006658,-0.229448,-0.503743,0.577768,-0.185844,0.799192,-0.298259,1,0.395631,-0.610191,-1.161842,-0.734031,-0.586779,-0.519468,0.449242,-0.890359,0
6,-1.189662,-0.557892,-1.006658,0.825453,1.434125,0.407257,0.486443,-0.010359,0.740092,1,0.136459,-0.527410,-1.161842,-0.556745,-0.586779,-0.519468,1.716794,0.627319,0

In [74]:
X_test_rnn , y_test_rnn = np.array(X_test_rnn).astype('float32') , np.array(y_test_rnn).astype('float32')

In [75]:
X_test_rnn.shape

(1771, 5, 19)

In [76]:
y_test_rnn.shape

(1771,)

In [77]:
y_pred = regressor.predict(X_test_rnn)

56/56 [==============================] - 2s 5ms/step

In [78]:
y_pred_series = []

for element in y_pred:
  if(element[0]>=0.5):
    y_pred_series.append(1)
  else:
    y_pred_series.append(0)


y_pred_series = np.array(y_pred_series).astype('float32')
y_pred_series

array([0., 0., 0., ..., 1., 0., 1.], dtype=float32)

In [79]:
y_pred_series.shape

(1771,)

In [80]:
from sklearn.metrics import confusion_matrix , classification_report
print("Classification Report: \n", classification_report(y_test_rnn, y_pred_series))

Classification Report:
               precision    recall  f1-score   support

         0.0       0.72      0.73      0.73      1239
         1.0       0.35      0.34      0.35       532

    accuracy                           0.62      1771
   macro avg       0.54      0.54      0.54      1771
weighted avg       0.61      0.62      0.61      1771