In [1]:
print("PRAISE THE LORD ALMIGHTY FATHER Thank You JESUS Praise You JESUS Forever May the HOLY SPIRIT Guide Us MOTHER MARY PRAY For Us SAINT JOSEPH, PRAY For Us SAINT ANTHONY PRAY For Us GOD BLESS !!! üß°‚õ™‚úù‚õ™üß°")

PRAISE THE LORD ALMIGHTY FATHER Thank You JESUS Praise You JESUS Forever May the HOLY SPIRIT Guide Us MOTHER MARY PRAY For Us SAINT JOSEPH, PRAY For Us SAINT ANTHONY PRAY For Us GOD BLESS !!! üß°‚õ™‚úù‚õ™üß°

## This Notebook includes work to analyse multiple columns after pre processing data with null values and only last 10 overs

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [3]:
df_matches = pd.read_csv('2022_to_2023_all_matches_preprocessed_v1.csv')
## New Pre Processed Data set Read.

## Checking Null Values

In [4]:

# Iterate over the columns
for column in df_matches.columns:
    # Count the number of null values in the column
    null_count = df_matches[column].isnull().sum()

    # Display the column name and the number of null values
    print(f"Column '{column}' has {null_count} null values.")

Column 'Unnamed: 0.1' has 0 null values.
Column 'Unnamed: 0' has 0 null values.
Column 'year' has 0 null values.
Column 'over_start_bowler_balls_bowled' has 0 null values.
Column 'over_start_bowler_wickets_taken' has 0 null values.
Column 'over_start_bowler_runs_given' has 0 null values.
Column 'over_start_batsman_on_strike_fours' has 0 null values.
Column 'over_start_batsman_on_strike_sixers' has 0 null values.
Column 'over_start_batsman_off_strike_balls_faced' has 0 null values.
Column 'over_start_batsman_on_strike_balls_faced' has 0 null values.
Column 'over_start_batsman_offstrike_runs' has 0 null values.
Column 'over_start_batsman_onstrike_runs' has 0 null values.
Column 'innings' has 0 null values.
Column 'match_num' has 0 null values.
Column 'country' has 0 null values.
Column 'target' has 0 null values.
Column 'req_run_rate' has 0 null values.
Column 'over_start_run_rate' has 0 null values.
Column 'over_start_total_score' has 0 null values.
Column 'over_start_total_wickets_fallen' has 0 null values.
Column 'over' has 0 null values.
Column 'Bowler' has 0 null values.
Column 'batter_onStrike' has 0 null values.
Column 'batter_offstrike' has 0 null values.
Column 'wickets_fallen' has 0 null values.
Column 'sixers' has 0 null values.
Column 'fours' has 0 null values.
Column 'total_runs' has 0 null values.
Column 'bat_on_str_Ave' has 0 null values.
Column 'bat_on_str_SR' has 0 null values.
Column 'bat_on_str_100' has 0 null values.
Column 'bat_on_str_50' has 0 null values.
Column 'bat_on_str_0' has 0 null values.
Column 'bat_on_str_4s' has 0 null values.
Column 'bat_on_str_6s' has 0 null values.
Column 'bat_on_str_Mat' has 0 null values.
Column 'bat_on_str_Inns' has 0 null values.
Column 'bat_on_str_NO' has 0 null values.
Column 'bat_on_str_Runs' has 0 null values.
Column 'bat_on_str_HS' has 0 null values.
Column 'bat_on_str_BF' has 0 null values.
Column 'bowler_Mat' has 0 null values.
Column 'bowler_Inns' has 0 null values.
Column 'bowler_Overs' has 0 null values.
Column 'bowler_Mdns' has 0 null values.
Column 'bowler_Runs' has 0 null values.
Column 'bowler_Wkts' has 0 null values.
Column 'bowler_Ave' has 0 null values.
Column 'bowler_Econ' has 0 null values.
Column 'bowler_SR' has 0 null values.
Column 'bowler_4w' has 0 null values.
Column 'bowler_5w' has 0 null values.
Column 'bat_off_str_Ave' has 0 null values.
Column 'bat_off_str_SR' has 0 null values.
Column 'bat_off_str_100' has 0 null values.
Column 'y_is_wicket_fallen' has 0 null values.
Column 'bat_off_str_50' has 0 null values.
Column 'bat_off_str_0' has 0 null values.
Column 'bat_off_str_4s' has 0 null values.
Column 'bat_off_str_6s' has 0 null values.
Column 'bat_off_str_Mat' has 0 null values.
Column 'bat_off_str_Inns' has 0 null values.
Column 'bat_off_str_NO' has 0 null values.
Column 'bat_off_str_Runs' has 0 null values.
Column 'bat_off_str_HS' has 0 null values.
Column 'bat_off_str_BF' has 0 null values.
Column 'date' has 0 null values.

In [5]:
df_matches.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'year', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'match_num', 'country', 'target', 'req_run_rate',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'Bowler', 'batter_onStrike',
       'batter_offstrike', 'wickets_fallen', 'sixers', 'fours', 'total_runs',
       'bat_on_str_Ave', 'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50',
       'bat_on_str_0', 'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat',
       'bat_on_str_Inns', 'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS',
       'bat_on_str_BF', 'bowler_Mat', 'bowler_Inns', 'bowler_Overs',
       'bowler_Mdns', 'bowler_Runs', 'bowler_Wkts', 'bowler_Ave',
       'bowler_Econ', 'bowler_SR', 'bowler_4w', 'bowler_5w', 'bat_off_str_Ave',
       'bat_off_str_SR', 'bat_off_str_100', 'y_is_wicket_fallen',
       'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s', 'bat_off_str_6s',
       'bat_off_str_Mat', 'bat_off_str_Inns', 'bat_off_str_NO',
       'bat_off_str_Runs', 'bat_off_str_HS', 'bat_off_str_BF', 'date'],
      dtype='object')

In [6]:
df_matches = df_matches[['date','over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings','target', 'req_run_rate',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs','bat_on_str_Ave', 'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50',
       'bat_on_str_0', 'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat',
       'bat_on_str_Inns', 'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS',
       'bat_on_str_BF', 'bowler_Mat', 'bowler_Inns', 'bowler_Overs',
       'bowler_Mdns', 'bowler_Runs', 'bowler_Wkts', 'bowler_Ave',
       'bowler_Econ', 'bowler_SR', 'bowler_4w', 'bowler_5w', 'bat_off_str_Ave',
       'bat_off_str_SR', 'bat_off_str_100','bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s', 'bat_off_str_6s',
       'bat_off_str_Mat', 'bat_off_str_Inns', 'bat_off_str_NO',
       'bat_off_str_Runs', 'bat_off_str_HS', 'bat_off_str_BF','y_is_wicket_fallen', 'match_num',]]

df_matches

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
0,2015-11-26,0,0,0,0,0,0,0,0,0,...,114.000000,35.000000,35.000000,35.000000,5.000000,1092.000000,116.000000,797.0000,0,468
1,2015-11-26,0,0,0,0,0,3,3,1,4,...,114.000000,35.000000,35.000000,35.000000,5.000000,1092.000000,116.000000,797.0000,1,468
2,2015-11-26,6,0,5,1,0,0,6,0,6,...,69.178322,28.380821,36.585675,32.818811,5.740116,771.773217,69.867867,589.3779,1,468
3,2015-11-26,7,1,11,0,0,3,0,0,0,...,14.000000,4.000000,8.000000,8.000000,1.000000,129.000000,72.000000,101.0000,1,468
4,2015-11-26,12,1,7,0,0,1,2,0,0,...,105.000000,51.000000,52.000000,51.000000,10.000000,1225.000000,85.000000,914.0000,0,468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,6,0,19,5,0,19,36,20,46,...,10.000000,2.000000,2.000000,2.000000,0.000000,104.000000,63.000000,78.0000,1,665
19106,2018-04-03,12,1,15,0,0,20,1,21,1,...,10.000000,2.000000,2.000000,2.000000,0.000000,104.000000,63.000000,78.0000,0,665
19107,2018-04-03,12,1,26,2,0,6,21,2,22,...,1.000000,1.000000,2.000000,2.000000,0.000000,15.000000,14.000000,10.0000,0,665
19108,2018-04-03,18,1,21,1,0,24,11,26,8,...,10.000000,2.000000,2.000000,2.000000,0.000000,104.000000,63.000000,78.0000,0,665
19109,2018-04-03,12,0,22,1,0,26,15,27,14,...,10.000000,2.000000,2.000000,2.000000,0.000000,104.000000,63.000000,78.0000,0,665

In [7]:
df_matches.info()
df_matches['date'] = pd.to_datetime(df_matches['date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19110 entries, 0 to 19109
Data columns (total 60 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   date                                       19110 non-null  object
 1   over_start_bowler_balls_bowled             19110 non-null  int64
 2   over_start_bowler_wickets_taken            19110 non-null  int64
 3   over_start_bowler_runs_given               19110 non-null  int64
 4   over_start_batsman_on_strike_fours         19110 non-null  int64
 5   over_start_batsman_on_strike_sixers        19110 non-null  int64
 6   over_start_batsman_off_strike_balls_faced  19110 non-null  int64
 7   over_start_batsman_on_strike_balls_faced   19110 non-null  int64
 8   over_start_batsman_offstrike_runs          19110 non-null  int64
 9   over_start_batsman_onstrike_runs           19110 non-null  int64
 10  innings                                    19110 non-null  int64
 11  target                                     19110 non-null  int64
 12  req_run_rate                               19110 non-null  float64
 13  over_start_run_rate                        19110 non-null  float64
 14  over_start_total_score                     19110 non-null  int64
 15  over_start_total_wickets_fallen            19110 non-null  int64
 16  over                                       19110 non-null  int64
 17  wickets_fallen                             19110 non-null  float64
 18  sixers                                     19110 non-null  float64
 19  fours                                      19110 non-null  float64
 20  total_runs                                 19110 non-null  float64
 21  bat_on_str_Ave                             19110 non-null  float64
 22  bat_on_str_SR                              19110 non-null  float64
 23  bat_on_str_100                             19110 non-null  float64
 24  bat_on_str_50                              19110 non-null  float64
 25  bat_on_str_0                               19110 non-null  float64
 26  bat_on_str_4s                              19110 non-null  float64
 27  bat_on_str_6s                              19110 non-null  float64
 28  bat_on_str_Mat                             19110 non-null  float64
 29  bat_on_str_Inns                            19110 non-null  float64
 30  bat_on_str_NO                              19110 non-null  float64
 31  bat_on_str_Runs                            19110 non-null  float64
 32  bat_on_str_HS                              19110 non-null  float64
 33  bat_on_str_BF                              19110 non-null  float64
 34  bowler_Mat                                 19110 non-null  float64
 35  bowler_Inns                                19110 non-null  float64
 36  bowler_Overs                               19110 non-null  float64
 37  bowler_Mdns                                19110 non-null  float64
 38  bowler_Runs                                19110 non-null  float64
 39  bowler_Wkts                                19110 non-null  float64
 40  bowler_Ave                                 19110 non-null  float64
 41  bowler_Econ                                19110 non-null  float64
 42  bowler_SR                                  19110 non-null  float64
 43  bowler_4w                                  19110 non-null  float64
 44  bowler_5w                                  19110 non-null  float64
 45  bat_off_str_Ave                            19110 non-null  float64
 46  bat_off_str_SR                             19110 non-null  float64
 47  bat_off_str_100                            19110 non-null  float64
 48  bat_off_str_50                             19110 non-null  float64
 49  bat_off_str_0                              19110 non-null  float64
 50  bat_off_str_4s                             19110 non-null  float64
 51  bat_off_str_6s                             19110 non-null  float64
 52  bat_off_str_Mat                            19110 non-null  float64
 53  bat_off_str_Inns                           19110 non-null  float64
 54  bat_off_str_NO                             19110 non-null  float64
 55  bat_off_str_Runs                           19110 non-null  float64
 56  bat_off_str_HS                             19110 non-null  float64
 57  bat_off_str_BF                             19110 non-null  float64
 58  y_is_wicket_fallen                         19110 non-null  int64
 59  match_num                                  19110 non-null  int64
dtypes: float64(43), int64(16), object(1)
memory usage: 8.7+ MB

In [8]:
# Filter the DataFrame for values greater than a specific date
specific_date = pd.to_datetime('2017-01-01')
df_matches = df_matches[df_matches['date'] > specific_date]

In [9]:
#Getting the total matches
# Get the unique values in the 'column_name' column
match_list = df_matches['match_num'].unique()

# Display the unique values
print(len(match_list))

361

In [10]:
df_matches.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'target', 'req_run_rate', 'over_start_run_rate',
       'over_start_total_score', 'over_start_total_wickets_fallen', 'over',
       'wickets_fallen', 'sixers', 'fours', 'total_runs', 'bat_on_str_Ave',
       'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50', 'bat_on_str_0',
       'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat', 'bat_on_str_Inns',
       'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS', 'bat_on_str_BF',
       'bowler_Mat', 'bowler_Inns', 'bowler_Overs', 'bowler_Mdns',
       'bowler_Runs', 'bowler_Wkts', 'bowler_Ave', 'bowler_Econ', 'bowler_SR',
       'bowler_4w', 'bowler_5w', 'bat_off_str_Ave', 'bat_off_str_SR',
       'bat_off_str_100', 'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s',
       'bat_off_str_6s', 'bat_off_str_Mat', 'bat_off_str_Inns',
       'bat_off_str_NO', 'bat_off_str_Runs', 'bat_off_str_HS',
       'bat_off_str_BF', 'y_is_wicket_fallen', 'match_num'],
      dtype='object')

In [11]:
## Select Data for Training

In [12]:
df_final = df_matches[['date','over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings','over_start_run_rate',
       'over_start_total_score','over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs','bat_on_str_Ave',
       'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50', 'bat_on_str_0',
       'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat', 'bat_on_str_Inns',
       'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS', 'bat_on_str_BF',
       'bowler_Mat', 'bowler_Inns', 'bowler_Overs', 'bowler_Mdns',
       'bowler_Runs', 'bowler_Wkts', 'bowler_Ave', 'bowler_Econ', 'bowler_SR',
       'bowler_4w', 'bowler_5w', 'bat_off_str_Ave', 'bat_off_str_SR',
       'bat_off_str_100', 'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s',
       'bat_off_str_6s', 'bat_off_str_Mat', 'bat_off_str_Inns',
       'bat_off_str_NO', 'bat_off_str_Runs', 'bat_off_str_HS',
       'bat_off_str_BF','y_is_wicket_fallen','match_num']]

In [13]:
df_final

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
40,2021-10-24,0,0,0,0,0,0,0,0,0,...,252.0,133.0,111.0,103.0,15.0,2864.0,118.0,2061.0,1,1361
41,2021-10-24,0,0,0,0,0,3,2,1,1,...,138.0,63.0,49.0,45.0,6.0,1557.0,110.0,1095.0,0,1361
42,2021-10-24,6,1,2,0,0,4,7,3,3,...,285.0,90.0,90.0,84.0,24.0,3159.0,94.0,2272.0,1,1361
43,2021-10-24,6,0,4,0,0,4,5,7,4,...,14.0,7.0,4.0,3.0,0.0,139.0,57.0,82.0,0,1361
44,2021-10-24,12,2,10,0,0,6,9,11,6,...,14.0,7.0,4.0,3.0,0.0,139.0,57.0,82.0,0,1361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,6,0,19,5,0,19,36,20,46,...,10.0,2.0,2.0,2.0,0.0,104.0,63.0,78.0,1,665
19106,2018-04-03,12,1,15,0,0,20,1,21,1,...,10.0,2.0,2.0,2.0,0.0,104.0,63.0,78.0,0,665
19107,2018-04-03,12,1,26,2,0,6,21,2,22,...,1.0,1.0,2.0,2.0,0.0,15.0,14.0,10.0,0,665
19108,2018-04-03,18,1,21,1,0,24,11,26,8,...,10.0,2.0,2.0,2.0,0.0,104.0,63.0,78.0,0,665
19109,2018-04-03,12,0,22,1,0,26,15,27,14,...,10.0,2.0,2.0,2.0,0.0,104.0,63.0,78.0,0,665

In [14]:
df_final.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'wickets_fallen', 'sixers',
       'fours', 'total_runs', 'bat_on_str_Ave', 'bat_on_str_SR',
       'bat_on_str_100', 'bat_on_str_50', 'bat_on_str_0', 'bat_on_str_4s',
       'bat_on_str_6s', 'bat_on_str_Mat', 'bat_on_str_Inns', 'bat_on_str_NO',
       'bat_on_str_Runs', 'bat_on_str_HS', 'bat_on_str_BF', 'bowler_Mat',
       'bowler_Inns', 'bowler_Overs', 'bowler_Mdns', 'bowler_Runs',
       'bowler_Wkts', 'bowler_Ave', 'bowler_Econ', 'bowler_SR', 'bowler_4w',
       'bowler_5w', 'bat_off_str_Ave', 'bat_off_str_SR', 'bat_off_str_100',
       'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s', 'bat_off_str_6s',
       'bat_off_str_Mat', 'bat_off_str_Inns', 'bat_off_str_NO',
       'bat_off_str_Runs', 'bat_off_str_HS', 'bat_off_str_BF',
       'y_is_wicket_fallen', 'match_num'],
      dtype='object')

In [15]:
cols_to_scale = ['over_start_bowler_balls_bowled', 'over_start_bowler_wickets_taken',
       'over_start_bowler_runs_given', 'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over','wickets_fallen', 'sixers', 'fours', 'total_runs','bat_on_str_Ave',
       'bat_on_str_SR', 'bat_on_str_100', 'bat_on_str_50', 'bat_on_str_0',
       'bat_on_str_4s', 'bat_on_str_6s', 'bat_on_str_Mat', 'bat_on_str_Inns',
       'bat_on_str_NO', 'bat_on_str_Runs', 'bat_on_str_HS', 'bat_on_str_BF',
       'bowler_Mat', 'bowler_Inns', 'bowler_Overs', 'bowler_Mdns',
       'bowler_Runs', 'bowler_Wkts', 'bowler_Ave', 'bowler_Econ', 'bowler_SR',
       'bowler_4w', 'bowler_5w', 'bat_off_str_Ave', 'bat_off_str_SR',
       'bat_off_str_100', 'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s',
       'bat_off_str_6s', 'bat_off_str_Mat', 'bat_off_str_Inns',
       'bat_off_str_NO', 'bat_off_str_Runs', 'bat_off_str_HS',
       'bat_off_str_BF',]

In [16]:
train_test_Date = pd.to_datetime('2022-01-01')
filtered_df = df_final[df_final['date'] > train_test_Date]
filtered_df

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
798,2022-01-29,0,0,0,0,0,0,0,0,0,...,26.0,16.0,12.0,12.0,0.0,307.0,73.0,205.0,0,1456
799,2022-01-29,0,0,0,0,0,2,4,4,3,...,26.0,16.0,12.0,12.0,0.0,307.0,73.0,205.0,1,1456
800,2022-01-29,6,0,7,0,0,0,8,0,4,...,38.0,11.0,15.0,15.0,0.0,374.0,59.0,300.0,0,1456
801,2022-01-29,6,1,1,1,0,2,12,0,9,...,38.0,11.0,15.0,15.0,0.0,374.0,59.0,300.0,0,1456
802,2022-01-29,12,0,12,0,0,18,2,11,0,...,142.0,64.0,56.0,56.0,1.0,1386.0,78.0,961.0,0,1456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,9,0,15,0,0,7,3,5,4,...,93.0,66.0,84.0,79.0,18.0,1305.0,74.0,1073.0,1,1986
5913,2023-01-07,13,2,15,0,0,0,8,0,6,...,15.0,12.0,40.0,33.0,16.0,291.0,31.0,272.0,0,1986
5914,2023-01-07,20,1,27,0,2,0,14,0,21,...,15.0,12.0,40.0,33.0,16.0,291.0,31.0,272.0,1,1986
5915,2023-01-07,15,1,21,0,2,3,15,2,22,...,1.0,2.0,34.0,13.0,6.0,32.0,11.0,37.0,1,1986
5916,2023-01-07,16,1,18,0,2,3,16,8,23,...,0.0,0.0,15.0,6.0,3.0,21.0,8.0,48.0,1,1986

In [17]:
from sklearn.model_selection import train_test_split
X_train = df_final[df_final['date'] <= train_test_Date]

In [18]:
test_Date = pd.to_datetime('2022-01-01')
X_test  =  df_final[df_final['date'] > test_Date]
X_test

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
798,2022-01-29,0,0,0,0,0,0,0,0,0,...,26.0,16.0,12.0,12.0,0.0,307.0,73.0,205.0,0,1456
799,2022-01-29,0,0,0,0,0,2,4,4,3,...,26.0,16.0,12.0,12.0,0.0,307.0,73.0,205.0,1,1456
800,2022-01-29,6,0,7,0,0,0,8,0,4,...,38.0,11.0,15.0,15.0,0.0,374.0,59.0,300.0,0,1456
801,2022-01-29,6,1,1,1,0,2,12,0,9,...,38.0,11.0,15.0,15.0,0.0,374.0,59.0,300.0,0,1456
802,2022-01-29,12,0,12,0,0,18,2,11,0,...,142.0,64.0,56.0,56.0,1.0,1386.0,78.0,961.0,0,1456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,9,0,15,0,0,7,3,5,4,...,93.0,66.0,84.0,79.0,18.0,1305.0,74.0,1073.0,1,1986
5913,2023-01-07,13,2,15,0,0,0,8,0,6,...,15.0,12.0,40.0,33.0,16.0,291.0,31.0,272.0,0,1986
5914,2023-01-07,20,1,27,0,2,0,14,0,21,...,15.0,12.0,40.0,33.0,16.0,291.0,31.0,272.0,1,1986
5915,2023-01-07,15,1,21,0,2,3,15,2,22,...,1.0,2.0,34.0,13.0,6.0,32.0,11.0,37.0,1,1986
5916,2023-01-07,16,1,18,0,2,3,16,8,23,...,0.0,0.0,15.0,6.0,3.0,21.0,8.0,48.0,1,1986

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

C:\Users\Arul\AppData\Local\Temp\ipykernel_26076\4151951648.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

In [20]:
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

C:\Users\Arul\AppData\Local\Temp\ipykernel_26076\2855813504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

In [21]:
X_train['match_num']

40       1361
41       1361
42       1361
43       1361
44       1361
         ...
19105     665
19106     665
19107     665
19108     665
19109     665
Name: match_num, Length: 10002, dtype: int64

In [22]:
match_list

array([1361, 1374, 1381, 1377, 1390, 1392, 1391, 1398, 1400, 1402, 1415,
       1420, 1428, 1434, 1440, 1443,  654, 1110, 1448, 1450, 1456, 1457,
       1174, 1179, 1208, 1366, 1454, 1379, 1375, 1216, 1176, 1455, 1384,
       1439, 1191, 1265, 1260, 1193, 1453, 1378, 1367, 1188, 1185, 1195,
       1178, 1369, 1192,  667, 1382, 1218, 1189, 1168, 1273, 1447, 1354,
       1222, 1446, 1458, 1449, 1351, 1357, 1467, 1466, 1470, 1473, 1492,
       1478, 1479, 1493, 1494, 1495, 1496, 1504, 1551, 1552, 1554, 1564,
       1569, 1571, 1572, 1607,  846, 1631, 1617, 1616, 1628, 1702, 1716,
       1698, 1693, 1720, 1718, 1725, 1726, 1728, 1732, 1735, 1750, 1753,
       1748, 1755, 1757, 1758, 1761, 1759, 1769, 1764, 1760, 1789, 1788,
       1795, 1794, 1798, 1793, 1796, 1803, 1801, 1804, 1802, 1800, 1806,
       1805, 1818, 1817, 1808, 1807, 1816, 1812, 1819, 1815, 1811, 1809,
       1850, 1845, 1840, 1842, 1839, 1847, 1858, 1853, 1856, 1860, 1861,
       1864, 1872, 1867, 1877, 1878, 1879, 1898, 1984, 1985, 1986,  669,
        625,  883, 1009, 1148, 1206, 1258,  605, 1243,  749,  686, 1031,
       1119,  690,  650,  763, 1146,  664, 1129,  659, 1000, 1032, 1116,
        653,  649,  617, 1075,  716, 1039,  615, 1118, 1002,  705,  714,
       1115,  993,  627,  693,  880,  647, 1113,  589, 1190, 1251,  892,
       1033, 1008, 1126, 1128, 1078,  712,  613,  661,  657,  639,  922,
       1207, 1139,  703, 1014,  702, 1114, 1140, 1096,  591,  655,  598,
        593, 1131,  622, 1121,  718,  618,  692, 1141,  684,  842,  735,
       1020,  658,  706,  689,  595,  688, 1111, 1046, 1212,  630,  632,
       1263, 1109,  893, 1165,  645,  711, 1123,  594,  646,  772, 1127,
        614, 1132,  701,  843,  708,  623, 1138, 1145,  597, 1015,  592,
       1120,  603, 1135,  575,  624,  707,  710,  660, 1022,  732,  636,
        709,  748,  914, 1181,  978,  668, 1124,  738,  607,  682,  704,
        638,  750, 1204,  679,  641,  715, 1024,  925,  734,  576,  992,
       1094,  633,  626, 1043,  663,  640, 1097, 1017, 1147, 1001,  717,
       1133,  736,  648,  604, 1026, 1095, 1041,  590,  602, 1117, 1007,
        606,  998, 1125,  662,  888,  878, 1122,  695,  631,  612,  635,
        611,  758,  651, 1093,  652,  596, 1270,  751, 1065,  628,  752,
        634,  642, 1108, 1180, 1027, 1210, 1130, 1037,  694, 1016,  988,
        629,  737,  879,  616, 1052,  656, 1034,  574,  665], dtype=int64)

In [23]:
X_train.columns

Index(['date', 'over_start_bowler_balls_bowled',
       'over_start_bowler_wickets_taken', 'over_start_bowler_runs_given',
       'over_start_batsman_on_strike_fours',
       'over_start_batsman_on_strike_sixers',
       'over_start_batsman_off_strike_balls_faced',
       'over_start_batsman_on_strike_balls_faced',
       'over_start_batsman_offstrike_runs', 'over_start_batsman_onstrike_runs',
       'innings', 'over_start_run_rate', 'over_start_total_score',
       'over_start_total_wickets_fallen', 'over', 'wickets_fallen', 'sixers',
       'fours', 'total_runs', 'bat_on_str_Ave', 'bat_on_str_SR',
       'bat_on_str_100', 'bat_on_str_50', 'bat_on_str_0', 'bat_on_str_4s',
       'bat_on_str_6s', 'bat_on_str_Mat', 'bat_on_str_Inns', 'bat_on_str_NO',
       'bat_on_str_Runs', 'bat_on_str_HS', 'bat_on_str_BF', 'bowler_Mat',
       'bowler_Inns', 'bowler_Overs', 'bowler_Mdns', 'bowler_Runs',
       'bowler_Wkts', 'bowler_Ave', 'bowler_Econ', 'bowler_SR', 'bowler_4w',
       'bowler_5w', 'bat_off_str_Ave', 'bat_off_str_SR', 'bat_off_str_100',
       'bat_off_str_50', 'bat_off_str_0', 'bat_off_str_4s', 'bat_off_str_6s',
       'bat_off_str_Mat', 'bat_off_str_Inns', 'bat_off_str_NO',
       'bat_off_str_Runs', 'bat_off_str_HS', 'bat_off_str_BF',
       'y_is_wicket_fallen', 'match_num'],
      dtype='object')

In [24]:
X_train

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
40,2021-10-24,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-1.041921,-1.102269,-0.879162,-0.926195,...,2.760329,3.556347,2.736870,2.724603,1.572656,2.972571,1.435068,2.811101,1,1361
41,2021-10-24,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-0.786672,-0.935825,-0.821465,-0.868854,...,1.040146,1.159872,0.457639,0.469304,0.062031,1.114192,1.198523,0.967095,0,1361
42,2021-10-24,-0.300797,0.987482,-0.795307,-0.752839,-0.496787,-0.701590,-0.519716,-0.706072,-0.754171,...,3.258277,2.084227,1.964873,1.985798,3.083280,3.392022,0.725432,3.213881,1,1361
43,2021-10-24,-0.300797,-0.554081,-0.583366,-0.752839,-0.496787,-0.701590,-0.686160,-0.475285,-0.696829,...,-0.830930,-0.757307,-1.196641,-1.163844,-0.945051,-0.902014,-0.368590,-0.966629,0,1361
44,2021-10-24,0.586774,2.529046,0.052455,-0.752839,-0.496787,-0.531424,-0.353273,-0.244498,-0.582146,...,-0.830930,-0.757307,-1.196641,-1.163844,-0.945051,-0.902014,-0.368590,-0.966629,0,1361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19105,2018-04-03,-0.300797,-0.554081,1.006188,1.876315,-0.496787,0.574654,1.893717,0.274772,1.711514,...,-0.891287,-0.928484,-1.270165,-1.202728,-0.945051,-0.951780,-0.191181,-0.974264,1,665
19106,2018-04-03,0.586774,0.987482,0.582307,-0.752839,-0.496787,0.659737,-1.019047,0.332468,-0.868854,...,-0.891287,-0.928484,-1.270165,-1.202728,-0.945051,-0.951780,-0.191181,-0.974264,0,665
19107,2018-04-03,0.586774,0.987482,1.747979,0.298822,-0.496787,-0.531424,0.645389,-0.763768,0.335318,...,-1.027091,-0.962720,-1.270165,-1.202728,-0.945051,-1.078326,-1.640021,-1.104070,0,665
19108,2018-04-03,1.474345,0.987482,1.218128,-0.227008,-0.496787,1.000069,-0.186829,0.620951,-0.467463,...,-0.891287,-0.928484,-1.270165,-1.202728,-0.945051,-0.951780,-0.191181,-0.974264,0,665
19109,2018-04-03,0.586774,-0.554081,1.324098,-0.227008,-0.496787,1.170235,0.146058,0.678648,-0.123414,...,-0.891287,-0.928484,-1.270165,-1.202728,-0.945051,-0.951780,-0.191181,-0.974264,0,665

In [25]:
o = 5
X_train[(X_train['match_num'] == 1456) & (X_train['innings'] == 1)].reset_index(drop=True).loc[o-5:o, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen']

Empty DataFrame
Columns: [over_start_bowler_balls_bowled, over_start_bowler_wickets_taken, over_start_bowler_runs_given, over_start_batsman_on_strike_fours, over_start_batsman_on_strike_sixers, over_start_batsman_off_strike_balls_faced, over_start_batsman_on_strike_balls_faced, over_start_batsman_offstrike_runs, over_start_batsman_onstrike_runs, innings, over_start_run_rate, over_start_total_score, over_start_total_wickets_fallen, over, wickets_fallen, sixers, fours, total_runs, bat_on_str_Ave, bat_on_str_SR, bat_on_str_100, bat_on_str_50, bat_on_str_0, bat_on_str_4s, bat_on_str_6s, bat_on_str_Mat, bat_on_str_Inns, bat_on_str_NO, bat_on_str_Runs, bat_on_str_HS, bat_on_str_BF, bowler_Mat, bowler_Inns, bowler_Overs, bowler_Mdns, bowler_Runs, bowler_Wkts, bowler_Ave, bowler_Econ, bowler_SR, bowler_4w, bowler_5w, bat_off_str_Ave, bat_off_str_SR, bat_off_str_100, bat_off_str_50, bat_off_str_0, bat_off_str_4s, bat_off_str_6s, bat_off_str_Mat, bat_off_str_Inns, bat_off_str_NO, bat_off_str_Runs, bat_off_str_HS, bat_off_str_BF, y_is_wicket_fallen]
Index: []

[0 rows x 56 columns]

### This Model Only analyses for the last 10 overs

In [26]:
match_list = X_train['match_num'].unique()

In [27]:
X_train_rnn = []
y_train_rnn = []

#Tracking down 5 previous overs

for match in match_list:
    print("In new Match" , match)
    for i in range(1,3):
        print("In new Innings" , i)
        innings_df = X_train[(X_train['match_num'] == match) & (X_train['innings'] == i)]
        print(len(innings_df))
        
        for over in range(10,len(innings_df)):
            
            X_train_rnn.append(innings_df.reset_index(drop=True).loc[over-10:over-1, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen'])
            y_train_rnn.append(innings_df.reset_index(drop=True).loc[over, 'y_is_wicket_fallen'])

In new Match 1361
In new Innings 1
20
In new Innings 2
18
In new Match 1374
In new Innings 1
20
In new Innings 2
17
In new Match 1381
In new Innings 1
20
In new Innings 2
15
In new Match 1377
In new Innings 1
20
In new Innings 2
19
In new Match 1390
In new Innings 1
20
In new Innings 2
20
In new Match 1392
In new Innings 1
20
In new Innings 2
20
In new Match 1391
In new Innings 1
15
In new Innings 2
7
In new Match 1398
In new Innings 1
20
In new Innings 2
17
In new Match 1400
In new Innings 1
20
In new Innings 2
20
In new Match 1402
In new Innings 1
20
In new Innings 2
19
In new Match 1415
In new Innings 1
20
In new Innings 2
19
In new Match 1420
In new Innings 1
20
In new Innings 2
19
In new Match 1428
In new Innings 1
20
In new Innings 2
19
In new Match 1434
In new Innings 1
20
In new Innings 2
20
In new Match 1440
In new Innings 1
20
In new Innings 2
18
In new Match 1443
In new Innings 1
20
In new Innings 2
19
In new Match 654
In new Innings 1
20
In new Innings 2
19
In new Match 1110
In new Innings 1
20
In new Innings 2
20
In new Match 1448
In new Innings 1
20
In new Innings 2
19
In new Match 1450
In new Innings 1
20
In new Innings 2
19
In new Match 1174
In new Innings 1
20
In new Innings 2
19
In new Match 1179
In new Innings 1
20
In new Innings 2
20
In new Match 1208
In new Innings 1
20
In new Innings 2
20
In new Match 1366
In new Innings 1
20
In new Innings 2
19
In new Match 1379
In new Innings 1
20
In new Innings 2
12
In new Match 1375
In new Innings 1
20
In new Innings 2
20
In new Match 1216
In new Innings 1
20
In new Innings 2
20
In new Match 1176
In new Innings 1
20
In new Innings 2
15
In new Match 1384
In new Innings 1
19
In new Innings 2
14
In new Match 1439
In new Innings 1
20
In new Innings 2
20
In new Match 1191
In new Innings 1
20
In new Innings 2
20
In new Match 1265
In new Innings 1
20
In new Innings 2
20
In new Match 1260
In new Innings 1
20
In new Innings 2
20
In new Match 1193
In new Innings 1
20
In new Innings 2
20
In new Match 1378
In new Innings 1
20
In new Innings 2
20
In new Match 1367
In new Innings 1
20
In new Innings 2
19
In new Match 1188
In new Innings 1
20
In new Innings 2
20
In new Match 1185
In new Innings 1
20
In new Innings 2
16
In new Match 1195
In new Innings 1
20
In new Innings 2
20
In new Match 1178
In new Innings 1
20
In new Innings 2
20
In new Match 1369
In new Innings 1
20
In new Innings 2
15
In new Match 1192
In new Innings 1
20
In new Innings 2
20
In new Match 667
In new Innings 1
20
In new Innings 2
19
In new Match 1382
In new Innings 1
20
In new Innings 2
19
In new Match 1218
In new Innings 1
20
In new Innings 2
19
In new Match 1189
In new Innings 1
20
In new Innings 2
15
In new Match 1168
In new Innings 1
20
In new Innings 2
17
In new Match 1273
In new Innings 1
20
In new Innings 2
15
In new Match 1447
In new Innings 1
20
In new Innings 2
20
In new Match 1354
In new Innings 1
15
In new Innings 2
9
In new Match 1222
In new Innings 1
20
In new Innings 2
14
In new Match 1446
In new Innings 1
20
In new Innings 2
18
In new Match 1449
In new Innings 1
20
In new Innings 2
20
In new Match 1351
In new Innings 1
20
In new Innings 2
20
In new Match 1357
In new Innings 1
20
In new Innings 2
19
In new Match 846
In new Innings 1
20
In new Innings 2
20
In new Match 669
In new Innings 1
20
In new Innings 2
20
In new Match 625
In new Innings 1
19
In new Innings 2
18
In new Match 883
In new Innings 1
20
In new Innings 2
20
In new Match 1009
In new Innings 1
20
In new Innings 2
12
In new Match 1148
In new Innings 1
20
In new Innings 2
20
In new Match 1206
In new Innings 1
20
In new Innings 2
20
In new Match 1258
In new Innings 1
20
In new Innings 2
20
In new Match 605
In new Innings 1
20
In new Innings 2
19
In new Match 1243
In new Innings 1
17
In new Innings 2
15
In new Match 749
In new Innings 1
20
In new Innings 2
20
In new Match 686
In new Innings 1
20
In new Innings 2
20
In new Match 1031
In new Innings 1
20
In new Innings 2
19
In new Match 1119
In new Innings 1
20
In new Innings 2
20
In new Match 690
In new Innings 1
20
In new Innings 2
19
In new Match 650
In new Innings 1
20
In new Innings 2
20
In new Match 763
In new Innings 1
20
In new Innings 2
16
In new Match 1146
In new Innings 1
20
In new Innings 2
14
In new Match 664
In new Innings 1
20
In new Innings 2
20
In new Match 1129
In new Innings 1
20
In new Innings 2
16
In new Match 659
In new Innings 1
19
In new Innings 2
18
In new Match 1000
In new Innings 1
20
In new Innings 2
20
In new Match 1032
In new Innings 1
20
In new Innings 2
20
In new Match 1116
In new Innings 1
20
In new Innings 2
20
In new Match 653
In new Innings 1
20
In new Innings 2
15
In new Match 649
In new Innings 1
20
In new Innings 2
19
In new Match 617
In new Innings 1
20
In new Innings 2
19
In new Match 1075
In new Innings 1
20
In new Innings 2
20
In new Match 716
In new Innings 1
20
In new Innings 2
20
In new Match 1039
In new Innings 1
20
In new Innings 2
20
In new Match 615
In new Innings 1
20
In new Innings 2
20
In new Match 1118
In new Innings 1
20
In new Innings 2
20
In new Match 1002
In new Innings 1
20
In new Innings 2
19
In new Match 705
In new Innings 1
20
In new Innings 2
20
In new Match 714
In new Innings 1
20
In new Innings 2
20
In new Match 1115
In new Innings 1
20
In new Innings 2
20
In new Match 993
In new Innings 1
20
In new Innings 2
18
In new Match 627
In new Innings 1
20
In new Innings 2
20
In new Match 693
In new Innings 1
20
In new Innings 2
20
In new Match 880
In new Innings 1
20
In new Innings 2
16
In new Match 647
In new Innings 1
20
In new Innings 2
20
In new Match 1113
In new Innings 1
20
In new Innings 2
18
In new Match 589
In new Innings 1
10
In new Innings 2
10
In new Match 1190
In new Innings 1
20
In new Innings 2
20
In new Match 1251
In new Innings 1
20
In new Innings 2
20
In new Match 892
In new Innings 1
20
In new Innings 2
19
In new Match 1033
In new Innings 1
20
In new Innings 2
17
In new Match 1008
In new Innings 1
20
In new Innings 2
17
In new Match 1126
In new Innings 1
20
In new Innings 2
14
In new Match 1128
In new Innings 1
20
In new Innings 2
19
In new Match 1078
In new Innings 1
20
In new Innings 2
17
In new Match 712
In new Innings 1
17
In new Innings 2
17
In new Match 613
In new Innings 1
20
In new Innings 2
20
In new Match 661
In new Innings 1
20
In new Innings 2
20
In new Match 657
In new Innings 1
20
In new Innings 2
19
In new Match 639
In new Innings 1
20
In new Innings 2
16
In new Match 922
In new Innings 1
20
In new Innings 2
19
In new Match 1207
In new Innings 1
20
In new Innings 2
15
In new Match 1139
In new Innings 1
20
In new Innings 2
20
In new Match 703
In new Innings 1
20
In new Innings 2
20
In new Match 1014
In new Innings 1
20
In new Innings 2
20
In new Match 702
In new Innings 1
20
In new Innings 2
20
In new Match 1114
In new Innings 1
20
In new Innings 2
20
In new Match 1140
In new Innings 1
18
In new Innings 2
16
In new Match 1096
In new Innings 1
20
In new Innings 2
19
In new Match 591
In new Innings 1
20
In new Innings 2
20
In new Match 655
In new Innings 1
20
In new Innings 2
20
In new Match 598
In new Innings 1
20
In new Innings 2
18
In new Match 593
In new Innings 1
20
In new Innings 2
20
In new Match 1131
In new Innings 1
20
In new Innings 2
16
In new Match 622
In new Innings 1
20
In new Innings 2
20
In new Match 1121
In new Innings 1
20
In new Innings 2
17
In new Match 718
In new Innings 1
20
In new Innings 2
17
In new Match 618
In new Innings 1
20
In new Innings 2
20
In new Match 692
In new Innings 1
20
In new Innings 2
10
In new Match 1141
In new Innings 1
10
In new Innings 2
10
In new Match 684
In new Innings 1
20
In new Innings 2
19
In new Match 842
In new Innings 1
20
In new Innings 2
18
In new Match 735
In new Innings 1
20
In new Innings 2
20
In new Match 1020
In new Innings 1
20
In new Innings 2
19
In new Match 658
In new Innings 1
20
In new Innings 2
20
In new Match 706
In new Innings 1
20
In new Innings 2
20
In new Match 689
In new Innings 1
20
In new Innings 2
20
In new Match 595
In new Innings 1
20
In new Innings 2
15
In new Match 688
In new Innings 1
20
In new Innings 2
20
In new Match 1111
In new Innings 1
20
In new Innings 2
20
In new Match 1046
In new Innings 1
20
In new Innings 2
15
In new Match 1212
In new Innings 1
20
In new Innings 2
19
In new Match 630
In new Innings 1
20
In new Innings 2
20
In new Match 632
In new Innings 1
8
In new Innings 2
8
In new Match 1263
In new Innings 1
20
In new Innings 2
20
In new Match 1109
In new Innings 1
20
In new Innings 2
20
In new Match 893
In new Innings 1
20
In new Innings 2
17
In new Match 1165
In new Innings 1
20
In new Innings 2
18
In new Match 645
In new Innings 1
20
In new Innings 2
19
In new Match 711
In new Innings 1
10
In new Innings 2
10
In new Match 1123
In new Innings 1
20
In new Innings 2
18
In new Match 594
In new Innings 1
20
In new Innings 2
17
In new Match 646
In new Innings 1
20
In new Innings 2
15
In new Match 772
In new Innings 1
20
In new Innings 2
20
In new Match 1127
In new Innings 1
20
In new Innings 2
19
In new Match 614
In new Innings 1
20
In new Innings 2
15
In new Match 1132
In new Innings 1
20
In new Innings 2
18
In new Match 701
In new Innings 1
20
In new Innings 2
17
In new Match 843
In new Innings 1
20
In new Innings 2
16
In new Match 708
In new Innings 1
20
In new Innings 2
17
In new Match 623
In new Innings 1
19
In new Innings 2
6
In new Match 1138
In new Innings 1
20
In new Innings 2
20
In new Match 1145
In new Innings 1
20
In new Innings 2
20
In new Match 597
In new Innings 1
20
In new Innings 2
20
In new Match 1015
In new Innings 1
20
In new Innings 2
20
In new Match 592
In new Innings 1
20
In new Innings 2
19
In new Match 1120
In new Innings 1
20
In new Innings 2
20
In new Match 603
In new Innings 1
20
In new Innings 2
20
In new Match 1135
In new Innings 1
20
In new Innings 2
20
In new Match 575
In new Innings 1
20
In new Innings 2
19
In new Match 624
In new Innings 1
20
In new Innings 2
16
In new Match 707
In new Innings 1
20
In new Innings 2
18
In new Match 710
In new Innings 1
20
In new Innings 2
20
In new Match 660
In new Innings 1
20
In new Innings 2
20
In new Match 1022
In new Innings 1
20
In new Innings 2
19
In new Match 732
In new Innings 1
20
In new Innings 2
20
In new Match 636
In new Innings 1
20
In new Innings 2
19
In new Match 709
In new Innings 1
20
In new Innings 2
20
In new Match 748
In new Innings 1
20
In new Innings 2
20
In new Match 914
In new Innings 1
20
In new Innings 2
18
In new Match 1181
In new Innings 1
20
In new Innings 2
20
In new Match 978
In new Innings 1
20
In new Innings 2
20
In new Match 668
In new Innings 1
20
In new Innings 2
19
In new Match 1124
In new Innings 1
20
In new Innings 2
20
In new Match 738
In new Innings 1
20
In new Innings 2
20
In new Match 607
In new Innings 1
20
In new Innings 2
18
In new Match 682
In new Innings 1
20
In new Innings 2
11
In new Match 704
In new Innings 1
20
In new Innings 2
20
In new Match 638
In new Innings 1
20
In new Innings 2
17
In new Match 750
In new Innings 1
20
In new Innings 2
19
In new Match 1204
In new Innings 1
20
In new Innings 2
19
In new Match 679
In new Innings 1
20
In new Innings 2
20
In new Match 641
In new Innings 1
20
In new Innings 2
20
In new Match 715
In new Innings 1
19
In new Innings 2
11
In new Match 1024
In new Innings 1
20
In new Innings 2
20
In new Match 925
In new Innings 1
20
In new Innings 2
20
In new Match 734
In new Innings 1
20
In new Innings 2
20
In new Match 576
In new Innings 1
20
In new Innings 2
20
In new Match 992
In new Innings 1
20
In new Innings 2
19
In new Match 1094
In new Innings 1
20
In new Innings 2
20
In new Match 633
In new Innings 1
20
In new Innings 2
16
In new Match 626
In new Innings 1
20
In new Innings 2
20
In new Match 1043
In new Innings 1
20
In new Innings 2
20
In new Match 663
In new Innings 1
20
In new Innings 2
14
In new Match 640
In new Innings 1
20
In new Innings 2
19
In new Match 1097
In new Innings 1
20
In new Innings 2
20
In new Match 1017
In new Innings 1
20
In new Innings 2
20
In new Match 1147
In new Innings 1
20
In new Innings 2
18
In new Match 1001
In new Innings 1
20
In new Innings 2
20
In new Match 717
In new Innings 1
20
In new Innings 2
17
In new Match 1133
In new Innings 1
20
In new Innings 2
19
In new Match 736
In new Innings 1
20
In new Innings 2
20
In new Match 648
In new Innings 1
20
In new Innings 2
17
In new Match 604
In new Innings 1
20
In new Innings 2
15
In new Match 1026
In new Innings 1
20
In new Innings 2
18
In new Match 1095
In new Innings 1
20
In new Innings 2
20
In new Match 1041
In new Innings 1
20
In new Innings 2
20
In new Match 590
In new Innings 1
20
In new Innings 2
20
In new Match 602
In new Innings 1
20
In new Innings 2
18
In new Match 1117
In new Innings 1
20
In new Innings 2
19
In new Match 1007
In new Innings 1
20
In new Innings 2
16
In new Match 606
In new Innings 1
20
In new Innings 2
19
In new Match 998
In new Innings 1
20
In new Innings 2
20
In new Match 1125
In new Innings 1
20
In new Innings 2
18
In new Match 662
In new Innings 1
20
In new Innings 2
20
In new Match 888
In new Innings 1
20
In new Innings 2
19
In new Match 878
In new Innings 1
20
In new Innings 2
20
In new Match 1122
In new Innings 1
20
In new Innings 2
19
In new Match 695
In new Innings 1
17
In new Innings 2
16
In new Match 631
In new Innings 1
20
In new Innings 2
20
In new Match 612
In new Innings 1
15
In new Innings 2
14
In new Match 635
In new Innings 1
20
In new Innings 2
20
In new Match 611
In new Innings 1
20
In new Innings 2
17
In new Match 758
In new Innings 1
20
In new Innings 2
20
In new Match 651
In new Innings 1
20
In new Innings 2
19
In new Match 1093
In new Innings 1
20
In new Innings 2
20
In new Match 652
In new Innings 1
20
In new Innings 2
20
In new Match 596
In new Innings 1
20
In new Innings 2
20
In new Match 1270
In new Innings 1
19
In new Innings 2
15
In new Match 751
In new Innings 1
20
In new Innings 2
12
In new Match 1065
In new Innings 1
20
In new Innings 2
16
In new Match 628
In new Innings 1
20
In new Innings 2
19
In new Match 752
In new Innings 1
13
In new Innings 2
11
In new Match 634
In new Innings 1
20
In new Innings 2
18
In new Match 642
In new Innings 1
20
In new Innings 2
12
In new Match 1108
In new Innings 1
16
In new Innings 2
16
In new Match 1180
In new Innings 1
20
In new Innings 2
20
In new Match 1027
In new Innings 1
20
In new Innings 2
16
In new Match 1210
In new Innings 1
20
In new Innings 2
20
In new Match 1130
In new Innings 1
20
In new Innings 2
19
In new Match 1037
In new Innings 1
20
In new Innings 2
20
In new Match 694
In new Innings 1
20
In new Innings 2
18
In new Match 1016
In new Innings 1
20
In new Innings 2
20
In new Match 988
In new Innings 1
19
In new Innings 2
14
In new Match 629
In new Innings 1
20
In new Innings 2
20
In new Match 737
In new Innings 1
20
In new Innings 2
19
In new Match 879
In new Innings 1
20
In new Innings 2
20
In new Match 616
In new Innings 1
20
In new Innings 2
20
In new Match 1052
In new Innings 1
20
In new Innings 2
20
In new Match 656
In new Innings 1
20
In new Innings 2
19
In new Match 1034
In new Innings 1
20
In new Innings 2
18
In new Match 574
In new Innings 1
20
In new Innings 2
18
In new Match 665
In new Innings 1
20
In new Innings 2
17

In [28]:
X_train_rnn[0]

,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,innings,...,bat_off_str_0,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen
0,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-1.041921,-1.102269,-0.879162,-0.926195,1,...,2.184417,2.760329,3.556347,2.736870,2.724603,1.572656,2.972571,1.435068,2.811101,1
1,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-0.786672,-0.935825,-0.821465,-0.868854,1,...,1.116379,1.040146,1.159872,0.457639,0.469304,0.062031,1.114192,1.198523,0.967095,0
2,-0.300797,0.987482,-0.795307,-0.752839,-0.496787,-0.701590,-0.519716,-0.706072,-0.754171,1,...,0.582360,3.258277,2.084227,1.964873,1.985798,3.083280,3.392022,0.725432,3.213881,1
3,-0.300797,-0.554081,-0.583366,-0.752839,-0.496787,-0.701590,-0.686160,-0.475285,-0.696829,1,...,-1.019696,-0.830930,-0.757307,-1.196641,-1.163844,-0.945051,-0.902014,-0.368590,-0.966629,0
4,0.586774,2.529046,0.052455,-0.752839,-0.496787,-0.531424,-0.353273,-0.244498,-0.582146,1,...,-1.019696,-0.830930,-0.757307,-1.196641,-1.163844,-0.945051,-0.902014,-0.368590,-0.966629,0
5,-1.188367,-0.554081,-1.007247,-0.752839,0.485396,-0.531424,0.146058,-0.244498,-0.066073,1,...,-1.019696,-0.830930,-0.757307,-1.196641,-1.163844,-0.945051,-0.902014,-0.368590,-0.966629,1
6,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,0.489571,-1.019047,0.274772,-0.868854,1,...,0.582360,3.258277,2.084227,1.964873,1.985798,3.083280,3.392022,0.725432,3.213881,0
7,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,0.489571,-0.519716,0.274772,-0.696829,1,...,0.582360,3.258277,2.084227,1.964873,1.985798,3.083280,3.392022,0.725432,3.213881,0
8,-0.300797,-0.554081,-0.689336,-0.227008,0.485396,-0.106009,0.562168,-0.532982,0.335318,1,...,0.582360,-0.453697,-0.278012,-0.130549,-0.152848,-0.105816,-0.371658,-0.132045,-0.329053,0
9,-0.300797,-0.554081,-0.583366,-0.227008,0.485396,0.234323,0.728611,-0.129105,0.450001,1,...,0.582360,-0.453697,-0.278012,-0.130549,-0.152848,-0.105816,-0.371658,-0.132045,-0.329053,0

In [29]:
X_train_rnn , y_train_rnn = np.array(X_train_rnn).astype('float32') , np.array(y_train_rnn).astype('float32')

In [30]:
X_train_rnn.shape

(4734, 10, 56)

In [31]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

# Initialising the RNN
regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train_rnn.shape[1], X_train_rnn.shape[2])))
regressor.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a third LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a fourth LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

# Adding the output layer
regressor.add(Dense(units = 1,activation='sigmoid'))

# Compiling the RNN
regressor.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [32]:
# Fitting the RNN to the Training set
regressor.fit(X_train_rnn, y_train_rnn, epochs = 100, batch_size = 32)

Epoch 1/100
148/148 [==============================] - 12s 21ms/step - loss: 0.6365 - accuracy: 0.6572
Epoch 2/100
148/148 [==============================] - 3s 20ms/step - loss: 0.6286 - accuracy: 0.6597
Epoch 3/100
148/148 [==============================] - 3s 21ms/step - loss: 0.6261 - accuracy: 0.6700
Epoch 4/100
148/148 [==============================] - 3s 20ms/step - loss: 0.6195 - accuracy: 0.6713
Epoch 5/100
148/148 [==============================] - 3s 21ms/step - loss: 0.6144 - accuracy: 0.6738
Epoch 6/100
148/148 [==============================] - 3s 21ms/step - loss: 0.6064 - accuracy: 0.6785
Epoch 7/100
148/148 [==============================] - 3s 21ms/step - loss: 0.5996 - accuracy: 0.6823
Epoch 8/100
148/148 [==============================] - 3s 20ms/step - loss: 0.5895 - accuracy: 0.6977
Epoch 9/100
148/148 [==============================] - 3s 20ms/step - loss: 0.5799 - accuracy: 0.7049
Epoch 10/100
148/148 [==============================] - 3s 22ms/step - loss: 0.5696 - accuracy: 0.7089
Epoch 11/100
148/148 [==============================] - 3s 20ms/step - loss: 0.5598 - accuracy: 0.7169
Epoch 12/100
148/148 [==============================] - 3s 21ms/step - loss: 0.5524 - accuracy: 0.7197
Epoch 13/100
148/148 [==============================] - 3s 21ms/step - loss: 0.5375 - accuracy: 0.7349
Epoch 14/100
148/148 [==============================] - 3s 21ms/step - loss: 0.5234 - accuracy: 0.7478
Epoch 15/100
148/148 [==============================] - 3s 20ms/step - loss: 0.5146 - accuracy: 0.7440
Epoch 16/100
148/148 [==============================] - 3s 21ms/step - loss: 0.4980 - accuracy: 0.7579
Epoch 17/100
148/148 [==============================] - 3s 22ms/step - loss: 0.4830 - accuracy: 0.7653
Epoch 18/100
148/148 [==============================] - 3s 20ms/step - loss: 0.4732 - accuracy: 0.7717
Epoch 19/100
148/148 [==============================] - 3s 21ms/step - loss: 0.4623 - accuracy: 0.7750
Epoch 20/100
148/148 [==============================] - 3s 21ms/step - loss: 0.4469 - accuracy: 0.7805
Epoch 21/100
148/148 [==============================] - 3s 21ms/step - loss: 0.4309 - accuracy: 0.7902
Epoch 22/100
148/148 [==============================] - 3s 20ms/step - loss: 0.4123 - accuracy: 0.7913
Epoch 23/100
148/148 [==============================] - 3s 21ms/step - loss: 0.4039 - accuracy: 0.7947
Epoch 24/100
148/148 [==============================] - 3s 21ms/step - loss: 0.3846 - accuracy: 0.8069
Epoch 25/100
148/148 [==============================] - 3s 21ms/step - loss: 0.3756 - accuracy: 0.8171
Epoch 26/100
148/148 [==============================] - 3s 21ms/step - loss: 0.3646 - accuracy: 0.8247
Epoch 27/100
148/148 [==============================] - 3s 22ms/step - loss: 0.3369 - accuracy: 0.8310
Epoch 28/100
148/148 [==============================] - 3s 21ms/step - loss: 0.3420 - accuracy: 0.8350
Epoch 29/100
148/148 [==============================] - 3s 22ms/step - loss: 0.3202 - accuracy: 0.8458
Epoch 30/100
148/148 [==============================] - 3s 23ms/step - loss: 0.3147 - accuracy: 0.8509
Epoch 31/100
148/148 [==============================] - 3s 23ms/step - loss: 0.3083 - accuracy: 0.8469
Epoch 32/100
148/148 [==============================] - 3s 23ms/step - loss: 0.2768 - accuracy: 0.8701
Epoch 33/100
148/148 [==============================] - 3s 23ms/step - loss: 0.2676 - accuracy: 0.8758
Epoch 34/100
148/148 [==============================] - 3s 23ms/step - loss: 0.2710 - accuracy: 0.8739
Epoch 35/100
148/148 [==============================] - 3s 23ms/step - loss: 0.2480 - accuracy: 0.8823
Epoch 36/100
148/148 [==============================] - 4s 24ms/step - loss: 0.2556 - accuracy: 0.8794
Epoch 37/100
148/148 [==============================] - 4s 25ms/step - loss: 0.2317 - accuracy: 0.8933
Epoch 38/100
148/148 [==============================] - 3s 23ms/step - loss: 0.2179 - accuracy: 0.8982
Epoch 39/100
148/148 [==============================] - 3s 23ms/step - loss: 0.1982 - accuracy: 0.9132
Epoch 40/100
148/148 [==============================] - 3s 22ms/step - loss: 0.2039 - accuracy: 0.9100
Epoch 41/100
148/148 [==============================] - 3s 21ms/step - loss: 0.2104 - accuracy: 0.9079
Epoch 42/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1859 - accuracy: 0.9174
Epoch 43/100
148/148 [==============================] - 3s 20ms/step - loss: 0.1712 - accuracy: 0.9271
Epoch 44/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1899 - accuracy: 0.9161
Epoch 45/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1745 - accuracy: 0.9282
Epoch 46/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1669 - accuracy: 0.9280
Epoch 47/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1518 - accuracy: 0.9349
Epoch 48/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1433 - accuracy: 0.9398
Epoch 49/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1564 - accuracy: 0.9368
Epoch 50/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1352 - accuracy: 0.9468
Epoch 51/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1213 - accuracy: 0.9508
Epoch 52/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1267 - accuracy: 0.9491
Epoch 53/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1416 - accuracy: 0.9449
Epoch 54/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1292 - accuracy: 0.9487
Epoch 55/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1087 - accuracy: 0.9550
Epoch 56/100
148/148 [==============================] - 3s 22ms/step - loss: 0.1158 - accuracy: 0.9565
Epoch 57/100
148/148 [==============================] - 3s 23ms/step - loss: 0.1082 - accuracy: 0.9563
Epoch 58/100
148/148 [==============================] - 3s 23ms/step - loss: 0.1055 - accuracy: 0.9603
Epoch 59/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0984 - accuracy: 0.9611
Epoch 60/100
148/148 [==============================] - 3s 21ms/step - loss: 0.1337 - accuracy: 0.9518
Epoch 61/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0955 - accuracy: 0.9637
Epoch 62/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0906 - accuracy: 0.9651
Epoch 63/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0903 - accuracy: 0.9685
Epoch 64/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0890 - accuracy: 0.9664
Epoch 65/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0890 - accuracy: 0.9651
Epoch 66/100
148/148 [==============================] - 4s 24ms/step - loss: 0.0913 - accuracy: 0.9660
Epoch 67/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0880 - accuracy: 0.9662
Epoch 68/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0866 - accuracy: 0.9687
Epoch 69/100
148/148 [==============================] - 3s 23ms/step - loss: 0.0646 - accuracy: 0.9804
Epoch 70/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0706 - accuracy: 0.9736
Epoch 71/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0840 - accuracy: 0.9708
Epoch 72/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0834 - accuracy: 0.9679
Epoch 73/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0827 - accuracy: 0.9698
Epoch 74/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0812 - accuracy: 0.9723
Epoch 75/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0744 - accuracy: 0.9721
Epoch 76/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0763 - accuracy: 0.9730
Epoch 77/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0678 - accuracy: 0.9755
Epoch 78/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0521 - accuracy: 0.9808
Epoch 79/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0769 - accuracy: 0.9711
Epoch 80/100
148/148 [==============================] - 3s 20ms/step - loss: 0.0611 - accuracy: 0.9795
Epoch 81/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0738 - accuracy: 0.9751
Epoch 82/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0662 - accuracy: 0.9763
Epoch 83/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0791 - accuracy: 0.9744
Epoch 84/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0511 - accuracy: 0.9808
Epoch 85/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0617 - accuracy: 0.9795
Epoch 86/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0650 - accuracy: 0.9791
Epoch 87/100
148/148 [==============================] - 3s 20ms/step - loss: 0.0432 - accuracy: 0.9865
Epoch 88/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0573 - accuracy: 0.9801
Epoch 89/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0433 - accuracy: 0.9875
Epoch 90/100
148/148 [==============================] - 3s 20ms/step - loss: 0.0786 - accuracy: 0.9719
Epoch 91/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0569 - accuracy: 0.9780
Epoch 92/100
148/148 [==============================] - 3s 20ms/step - loss: 0.0702 - accuracy: 0.9757
Epoch 93/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0543 - accuracy: 0.9818
Epoch 94/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0463 - accuracy: 0.9823
Epoch 95/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0497 - accuracy: 0.9812
Epoch 96/100
148/148 [==============================] - 3s 21ms/step - loss: 0.0547 - accuracy: 0.9823
Epoch 97/100
148/148 [==============================] - 3s 22ms/step - loss: 0.0608 - accuracy: 0.9806
Epoch 98/100
148/148 [==============================] - 3s 23ms/step - loss: 0.0575 - accuracy: 0.9787
Epoch 99/100
148/148 [==============================] - 3s 23ms/step - loss: 0.0535 - accuracy: 0.9808
Epoch 100/100
148/148 [==============================] - 4s 24ms/step - loss: 0.0501 - accuracy: 0.9829

In [33]:
X_test

,date,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,...,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen,match_num
798,2022-01-29,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-1.041921,-1.102269,-0.879162,-0.926195,...,-0.649858,-0.449189,-0.902547,-0.813884,-0.945051,-0.663141,0.104501,-0.731833,0,1456
799,2022-01-29,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-0.871755,-0.769382,-0.648375,-0.754171,...,-0.649858,-0.449189,-0.902547,-0.813884,-0.945051,-0.663141,0.104501,-0.731833,1,1456
800,2022-01-29,-0.300797,-0.554081,-0.265455,-0.752839,-0.496787,-1.041921,-0.436494,-0.879162,-0.696829,...,-0.468786,-0.620366,-0.792261,-0.697230,-0.945051,-0.567876,-0.309454,-0.550487,0,1456
801,2022-01-29,-0.300797,0.987482,-0.901277,-0.227008,-0.496787,-0.871755,-0.103607,-0.879162,-0.410122,...,-0.468786,-0.620366,-0.792261,-0.697230,-0.945051,-0.567876,-0.309454,-0.550487,0,1456
802,2022-01-29,0.586774,-0.554081,0.264396,-0.752839,-0.496787,0.489571,-0.935825,-0.244498,-0.926195,...,1.100504,1.194108,0.714972,0.897033,-0.777204,0.871053,0.252342,0.711302,0,1456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5912,2023-01-07,0.142989,-0.554081,0.582307,-0.752839,-0.496787,-0.446341,-0.852604,-0.590678,-0.696829,...,0.361127,1.262579,1.744302,1.791376,2.076197,0.755882,0.134069,0.925099,1,1986
5913,2023-01-07,0.734702,2.529046,0.582307,-0.752839,-0.496787,-1.041921,-0.436494,-0.879162,-0.582146,...,-0.815841,-0.586131,0.126783,0.002690,1.740503,-0.685891,-1.137362,-0.603936,0,1986
5914,2023-01-07,1.770201,0.987482,1.853950,-0.752839,1.467579,-1.041921,0.062837,-0.879162,0.277976,...,-0.815841,-0.586131,0.126783,0.002690,1.740503,-0.685891,-1.137362,-0.603936,1,1986
5915,2023-01-07,1.030559,0.987482,1.218128,-0.752839,1.467579,-0.786672,0.146058,-0.763768,0.335318,...,-1.027091,-0.928484,-0.093787,-0.774999,0.062031,-1.054154,-1.728725,-1.052530,1,1986
5916,2023-01-07,1.178488,0.987482,0.900217,-0.752839,1.467579,-0.786672,0.229280,-0.417588,0.392659,...,-1.042180,-0.996955,-0.792261,-1.047190,-0.441510,-1.069795,-1.817430,-1.031532,1,1986

In [34]:
## Testing Mechanism 
test_match_list = X_test['match_num'].unique()
test_match_list

array([1456, 1457, 1454, 1455, 1453, 1458, 1467, 1466, 1470, 1473, 1492,
       1478, 1479, 1493, 1494, 1495, 1496, 1504, 1551, 1552, 1554, 1564,
       1569, 1571, 1572, 1607, 1631, 1617, 1616, 1628, 1702, 1716, 1698,
       1693, 1720, 1718, 1725, 1726, 1728, 1732, 1735, 1750, 1753, 1748,
       1755, 1757, 1758, 1761, 1759, 1769, 1764, 1760, 1789, 1788, 1795,
       1794, 1798, 1793, 1796, 1803, 1801, 1804, 1802, 1800, 1806, 1805,
       1818, 1817, 1808, 1807, 1816, 1812, 1819, 1815, 1811, 1809, 1850,
       1845, 1840, 1842, 1839, 1847, 1858, 1853, 1856, 1860, 1861, 1864,
       1872, 1867, 1877, 1878, 1879, 1898, 1984, 1985, 1986], dtype=int64)

In [35]:
X_test_rnn = []
y_test_rnn = []

#Tracking down 5 previous overs

for match in test_match_list:
    print("In new Match" , match)
    for i in range(2,3):
        print("In new Innings" , i)
        innings_df = X_test[(X_test['match_num'] == match) & (X_test['innings'] == i)]
        print(len(innings_df))
        
        for over in range(10,len(innings_df)):
            
            X_test_rnn.append(innings_df.reset_index(drop=True).loc[over-10:over-1, 'over_start_bowler_balls_bowled':'y_is_wicket_fallen'])
            y_test_rnn.append(innings_df.reset_index(drop=True).loc[over, 'y_is_wicket_fallen'])

In new Match 1456
In new Innings 2
20
In new Match 1457
In new Innings 2
20
In new Match 1454
In new Innings 2
20
In new Match 1455
In new Innings 2
20
In new Match 1453
In new Innings 2
18
In new Match 1458
In new Innings 2
19
In new Match 1467
In new Innings 2
19
In new Match 1466
In new Innings 2
17
In new Match 1470
In new Innings 2
19
In new Match 1473
In new Innings 2
20
In new Match 1492
In new Innings 2
20
In new Match 1478
In new Innings 2
20
In new Match 1479
In new Innings 2
20
In new Match 1493
In new Innings 2
18
In new Match 1494
In new Innings 2
17
In new Match 1495
In new Innings 2
18
In new Match 1496
In new Innings 2
18
In new Match 1504
In new Innings 2
20
In new Match 1551
In new Innings 2
14
In new Match 1552
In new Innings 2
18
In new Match 1554
In new Innings 2
20
In new Match 1564
In new Innings 2
20
In new Match 1569
In new Innings 2
19
In new Match 1571
In new Innings 2
20
In new Match 1572
In new Innings 2
17
In new Match 1607
In new Innings 2
20
In new Match 1631
In new Innings 2
20
In new Match 1617
In new Innings 2
19
In new Match 1616
In new Innings 2
20
In new Match 1628
In new Innings 2
17
In new Match 1702
In new Innings 2
20
In new Match 1716
In new Innings 2
17
In new Match 1698
In new Innings 2
17
In new Match 1693
In new Innings 2
20
In new Match 1720
In new Innings 2
19
In new Match 1718
In new Innings 2
20
In new Match 1725
In new Innings 2
20
In new Match 1726
In new Innings 2
16
In new Match 1728
In new Innings 2
20
In new Match 1732
In new Innings 2
20
In new Match 1735
In new Innings 2
19
In new Match 1750
In new Innings 2
20
In new Match 1753
In new Innings 2
19
In new Match 1748
In new Innings 2
11
In new Match 1755
In new Innings 2
20
In new Match 1757
In new Innings 2
20
In new Match 1758
In new Innings 2
20
In new Match 1761
In new Innings 2
20
In new Match 1759
In new Innings 2
20
In new Match 1769
In new Innings 2
20
In new Match 1764
In new Innings 2
17
In new Match 1760
In new Innings 2
20
In new Match 1789
In new Innings 2
20
In new Match 1788
In new Innings 2
20
In new Match 1795
In new Innings 2
20
In new Match 1794
In new Innings 2
8
In new Match 1798
In new Innings 2
20
In new Match 1793
In new Innings 2
20
In new Match 1796
In new Innings 2
20
In new Match 1803
In new Innings 2
20
In new Match 1801
In new Innings 2
20
In new Match 1804
In new Innings 2
20
In new Match 1802
In new Innings 2
15
In new Match 1800
In new Innings 2
17
In new Match 1806
In new Innings 2
20
In new Match 1805
In new Innings 2
19
In new Match 1818
In new Innings 2
20
In new Match 1817
In new Innings 2
20
In new Match 1808
In new Innings 2
20
In new Match 1807
In new Innings 2
20
In new Match 1816
In new Innings 2
20
In new Match 1812
In new Innings 2
20
In new Match 1819
In new Innings 2
20
In new Match 1815
In new Innings 2
17
In new Match 1811
In new Innings 2
18
In new Match 1809
In new Innings 2
19
In new Match 1850
In new Innings 2
20
In new Match 1845
In new Innings 2
17
In new Match 1840
In new Innings 2
19
In new Match 1842
In new Innings 2
20
In new Match 1839
In new Innings 2
18
In new Match 1847
In new Innings 2
17
In new Match 1858
In new Innings 2
20
In new Match 1853
In new Innings 2
20
In new Match 1856
In new Innings 2
19
In new Match 1860
In new Innings 2
16
In new Match 1861
In new Innings 2
14
In new Match 1864
In new Innings 2
20
In new Match 1872
In new Innings 2
19
In new Match 1867
In new Innings 2
20
In new Match 1877
In new Innings 2
20
In new Match 1878
In new Innings 2
16
In new Match 1879
In new Innings 2
19
In new Match 1898
In new Innings 2
19
In new Match 1984
In new Innings 2
20
In new Match 1985
In new Innings 2
20
In new Match 1986
In new Innings 2
17

In [36]:
X_test_rnn[2]

,over_start_bowler_balls_bowled,over_start_bowler_wickets_taken,over_start_bowler_runs_given,over_start_batsman_on_strike_fours,over_start_batsman_on_strike_sixers,over_start_batsman_off_strike_balls_faced,over_start_batsman_on_strike_balls_faced,over_start_batsman_offstrike_runs,over_start_batsman_onstrike_runs,innings,...,bat_off_str_0,bat_off_str_4s,bat_off_str_6s,bat_off_str_Mat,bat_off_str_Inns,bat_off_str_NO,bat_off_str_Runs,bat_off_str_HS,bat_off_str_BF,y_is_wicket_fallen
2,-0.300797,-0.554081,-0.371426,-0.227008,-0.496787,-0.616507,-0.519716,-0.417588,-0.582146,2,...,-1.019696,-1.027091,-0.928484,-1.270165,-1.202728,-0.777204,-1.064107,-1.462612,-1.088799,0
3,-0.300797,-0.554081,-0.159485,-0.227008,-0.496787,-0.361258,-0.270051,-0.129105,-0.467463,2,...,-1.019696,-1.027091,-0.928484,-1.270165,-1.202728,-0.777204,-1.064107,-1.462612,-1.088799,0
4,-1.188367,-0.554081,-1.007247,-0.227008,1.467579,-0.106009,-0.020385,-0.359892,0.335318,2,...,0.048341,-0.453697,-0.620366,-0.718738,-0.658346,-0.777204,-0.636125,-0.072908,-0.665021,0
5,-1.188367,-0.554081,-1.007247,-0.227008,-0.496787,0.574654,-0.186829,1.313311,-0.410122,2,...,-1.019696,-1.027091,-0.928484,-1.270165,-1.202728,-0.777204,-1.064107,-1.462612,-1.088799,0
6,-1.188367,-0.554081,-1.007247,0.824653,-0.496787,0.659737,0.229280,1.313311,0.105952,2,...,-1.019696,-1.027091,-0.928484,-1.270165,-1.202728,-0.777204,-1.064107,-1.462612,-1.088799,0
7,0.586774,-0.554081,0.900217,1.350484,-0.496787,0.829903,0.562168,1.428705,0.392659,2,...,-1.019696,-1.027091,-0.928484,-1.270165,-1.202728,-0.777204,-1.064107,-1.462612,-1.088799,1
8,-0.300797,-0.554081,-0.265455,1.350484,-0.496787,-0.701590,0.645389,-0.763768,0.450001,2,...,0.048341,-0.001017,0.954460,0.567925,0.469304,0.229879,0.273869,0.015796,0.316158,0
9,1.474345,0.987482,1.218128,1.350484,-0.496787,-0.616507,1.061499,-0.706072,0.564684,2,...,0.048341,-0.001017,0.954460,0.567925,0.469304,0.229879,0.273869,0.015796,0.316158,1
10,0.586774,-0.554081,0.052455,-0.752839,-0.496787,-0.446341,-0.769382,-0.590678,-0.696829,2,...,0.048341,-0.001017,0.954460,0.567925,0.469304,0.229879,0.273869,0.015796,0.316158,1
11,-1.188367,-0.554081,-1.007247,-0.752839,-0.496787,-0.871755,-0.436494,-0.879162,-0.582146,2,...,0.048341,-0.861109,-0.551895,-0.130549,-0.425039,0.397726,-0.778312,-1.196498,-0.764285,0

In [37]:
X_test_rnn , y_test_rnn = np.array(X_test_rnn).astype('float32') , np.array(y_test_rnn).astype('float32')

In [38]:
X_test_rnn.shape

(857, 10, 56)

In [39]:
y_test_rnn.shape

(857,)

In [40]:
y_pred = regressor.predict(X_test_rnn)

27/27 [==============================] - 2s 7ms/step

In [41]:
y_pred_series = []

for element in y_pred:
  if(element[0]>=0.5):
    y_pred_series.append(1)
  else:
    y_pred_series.append(0)


y_pred_series = np.array(y_pred_series).astype('float32')
y_pred_series

array([1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [42]:
y_pred_series.shape

(857,)

In [43]:
from sklearn.metrics import confusion_matrix , classification_report
print("Classification Report: \n", classification_report(y_test_rnn, y_pred_series))

Classification Report:
               precision    recall  f1-score   support

         0.0       0.67      0.64      0.66       578
         1.0       0.32      0.35      0.34       279

    accuracy                           0.55       857
   macro avg       0.50      0.50      0.50       857
weighted avg       0.56      0.55      0.55       857